--Los 3 de circuitos con mayor consumo de combustible promedio.

CREATE VIEW COSMICOS.Circuitos_Mayor_Consumo AS
SELECT TOP 3 C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, AVG(T.TELE_AUTO_COMBUSTIBLE) AS COMBUSTIBLE_PROMEDIO FROM COSMICOS.TELEMETRIA T
JOIN COSMICOS.SECTOR S ON T.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO C ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE
ORDER BY AVG(T.TELE_AUTO_COMBUSTIBLE) 
-- dado que el dato de las telemetrias de "Combustible", corresponde a "Cantidad de combustible actual en el auto en lts",
-- entonces si tienen poco combustible es porque consumieron mas




-- Desgaste promedio de cada componente de cada auto por vuelta por circuito. 
-- Tener en cuenta que, para el cálculo del desgaste de los neumáticos, 
-- se toma la diferencia de mm del mismo entre la medición inicial y final de cada vuelta. 
-- Lo mismo aplica para el desgaste de frenos. Para el cálculo del desgaste del motor se toma en cuenta la perdida de potencia
CREATE VIEW COSMICOS.Desgastes_Por_Auto_Por_Vuelta_Por_Circuito AS
SELECT AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO,
		(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO1, -- hay 1 desgaste de neumatico y freno por auto por vuelta por circuito, 
							  -- asi que no hacemos literalmente un promedio, sino que, como indica la consigna
							  -- el "desgaste promedio" la diferencia de mm entre la medición inicial y final de cada vuelta
							  -- es decir, "max mm (medicion inicial) - min mm (medicion final)"
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO2, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO3, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO4,
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO1, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO2, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO3, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO4,
	(SELECT (MAX(TELE_MOTOR_POTENCIA) - MIN(TELE_MOTOR_POTENCIA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_MOTOR TM1 ON T1.CODIGO_TELE_MOTOR = TM1.CODIGO_TELE_MOTOR
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_MOTOR, 
	AVG (TC.TELE_CAJA_DESGASTE) AS DESGASTE_CAJA
FROM COSMICOS.TELEMETRIA T
JOIN COSMICOS.TELEMETRIA_CAJA TC ON T.CODIGO_TELE_CAJA = TC.CODIGO_TELE_CAJA
JOIN COSMICOS.AUTO_POR_CARRERA AC ON T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
JOIN COSMICOS.SECTOR S ON T.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO C ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
GROUP BY T.CODIGO_AUTO_POR_CARRERA, AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO
--ORDER BY AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO -- no se puede ordenar vistas, pero es de utilidad para visualizar en un select
