------------------------------------------------------ CREACION DE LAS DIMENSIONES ------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_DIMENSION_CIRCUITO] (
	[CIRCUITO_CODIGO] int PRIMARY KEY,
	[CIRCUITO_NOMBRE] nvarchar(255),
	[CIRCUITO_PAIS] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_SECTOR] (
	[CODIGO_TIPO_SECTOR] int PRIMARY KEY, 
	[DESCRIPCION] nvarchar(255),
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_ESCUDERIA] (
	[CODIGO_ESCUDERIA] int PRIMARY KEY, 
	[ESCUDERIA_NOMBRE] varchar(50),
	[ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIEMPO](
	[CODIGO_TIEMPO] int PRIMARY KEY IDENTITY(1,1),
	[CUATRIMESTRE] int,
	[ANIO] int
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE](
	[CODIGO_TIPO_INCIDENTE] int PRIMARY KEY,
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO](
	[CODIGO_TIPO_NEUMATICO] int PRIMARY KEY,
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_VUELTA](
	[CODIGO_VUELTA] int PRIMARY KEY IDENTITY(1,1),
	[NUMERO_VUELTA] decimal(18,0)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_AUTO] (
	[CODIGO_AUTO] int  PRIMARY KEY,
	[AUTO_NUMERO] int,
	[AUTO_MODELO] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_PILOTO] (
  [CODIGO_PILOTO] int PRIMARY KEY,
  [PILOTO_NOMBRE] varchar(50),
  [PILOTO_APELLIDO] varchar(50),
  [PILOTO_NACIONALIDAD] varchar(50)
)
GO

-------------------------------------------------------- CREACION DE LOS HECHOS ------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_HECHOS_AUTOS_Y_CARRERAS] (
	[CODIGO_VUELTA] int REFERENCES [COSMICOS].[BI_DIMENSION_VUELTA],
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_TIPO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_PILOTO] int REFERENCES [COSMICOS].[BI_DIMENSION_PILOTO],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[CODIGO_AUTO] int REFERENCES [COSMICOS].[BI_DIMENSION_AUTO],
	[DESGASTE_MOTOR] decimal(18,6),
	[DESGASTE_CAJA] decimal(18,6),
	[DESGASTE_NEUMATICO_1] decimal(18,6),
	[DESGASTE_NEUMATICO_2] decimal(18,6),
	[DESGASTE_NEUMATICO_3] decimal(18,6),
	[DESGASTE_NEUMATICO_4] decimal(18,6),
	[DESGASTE_FRENO_1] decimal(18,2),
	[DESGASTE_FRENO_2] decimal(18,2),
	[DESGASTE_FRENO_3] decimal(18,2),
	[DESGASTE_FRENO_4] decimal(18,2),
	[CONSUMO_COMBUSTIBLE] decimal (18,2),
	[MAXIMA_VELOCIDAD] decimal (18,2),
	[TIEMPO_VUELTA] decimal (18,10),
	CONSTRAINT PK_HECHOS_AUTOS_Y_CARRERAS PRIMARY KEY (CODIGO_VUELTA, CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR,
	CODIGO_ESCUDERIA, CODIGO_PILOTO, CODIGO_TIEMPO, CODIGO_AUTO)
)
GO

CREATE TABLE [COSMICOS].[BI_HECHOS_INCIDENTES] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_TIPO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[CODIGO_TIPO_INCIDENTE] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE],
	[CANTIDAD_INCIDENTES] int,
	CONSTRAINT PK_HECHOS_INCIDENTES PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, CODIGO_TIEMPO, CODIGO_TIPO_INCIDENTE)
)
GO

CREATE TABLE [COSMICOS].[BI_HECHOS_PARADAS] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[CODIGO_TIPO_NEU_VIEJO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO],
	[CODIGO_TIPO_NEU_NUEVO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO],
	[TIEMPO_PARADA] decimal(18,2),
	[CANTIDAD_PARADAS] int,
	CONSTRAINT PK_HECHOS_PARADAS PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_ESCUDERIA, CODIGO_TIEMPO, CODIGO_TIPO_NEU_VIEJO, CODIGO_TIPO_NEU_NUEVO)
)
GO


------------------------------------------------------ CARGA DE LAS DIMENSIONES ------------------------------------------------------

-- DIMENSION CIRCUITO
INSERT INTO [COSMICOS].[BI_DIMENSION_CIRCUITO] 
SELECT
  CIRCUITO_CODIGO,
  CIRCUITO_NOMBRE,
  CIRCUITO_PAIS 
FROM COSMICOS.CIRCUITO

-- DIMENSION TIPO SECTOR
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_SECTOR] 
SELECT
  SECTOR_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_SECTOR

-- DIMENSION ESCUDERIA
INSERT INTO [COSMICOS].[BI_DIMENSION_ESCUDERIA] 
SELECT
  CODIGO_ESCUDERIA, 
  ESCUDERIA_NOMBRE,
  ESCUDERIA_NACIONALIDAD
FROM COSMICOS.ESCUDERIA

-- DIMENSION TIEMPO
-- TOMADO DE LAS FECHAS DE CARRERA, QUE SE SUPONEN QUE SON LAS QUE EXISTEN
INSERT INTO [COSMICOS].[BI_DIMENSION_TIEMPO] (CUATRIMESTRE, ANIO) 
SELECT DISTINCT (CASE  
	WHEN MONTH(CARRERA_FECHA) >= 1 AND MONTH(CARRERA_FECHA) <= 4 THEN 1
	WHEN MONTH(CARRERA_FECHA) >= 5 AND MONTH(CARRERA_FECHA) <= 8 THEN 2
	WHEN MONTH(CARRERA_FECHA) >= 9 AND MONTH(CARRERA_FECHA) <= 12 THEN 3
	end) ,YEAR(CARRERA_FECHA)
FROM COSMICOS.CARRERA

-- DIMENSION TIPO INCIDENTE
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE]  
SELECT
  INCIDENTE_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_INCIDENTE 

-- DIMENSION TIPO NEUMATICO
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO]  
SELECT
  NEUMATICO_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_NEUMATICO 
	
-- DIMENSION AUTO
INSERT INTO [COSMICOS].[BI_DIMENSION_AUTO]  
SELECT
  AC.CODIGO_AUTO_POR_CARRERA,
  AUTO_NUMERO,
  AUTO_MODELO 
FROM COSMICOS.AUTO A
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = A.CODIGO_AUTO

-- DIMENSION PILOTO
INSERT INTO [COSMICOS].[BI_DIMENSION_PILOTO]
SELECT 
	CODIGO_PILOTO,
	PILOTO_NOMBRE,
	PILOTO_APELLIDO, 
	PILOTO_NACIONALIDAD
FROM COSMICOS.PILOTO

-- DIMENSION VUELTA
INSERT INTO [COSMICOS].[BI_DIMENSION_VUELTA]
SELECT DISTINCT 
	TELE_AUTO_NUMERO_VUELTA
FROM COSMICOS.TELEMETRIA
ORDER BY TELE_AUTO_NUMERO_VUELTA
GO

------------------------------------------------------ FUNCIONES AUXILIARES ------------------------------------------------------

CREATE FUNCTION COSMICOS.PK_Del_Tiempo (@fecha datetime)
RETURNS INT
AS
BEGIN
DECLARE @id INT;
	SET @id = (SELECT CODIGO_TIEMPO FROM BI_DIMENSION_TIEMPO
	WHERE ANIO = YEAR(@fecha) AND CUATRIMESTRE = (CASE  
		WHEN MONTH(@fecha) >= 1 AND MONTH(@fecha) <= 4 THEN 1
		WHEN MONTH(@fecha) >= 5 AND MONTH(@fecha) <= 8 THEN 2
		WHEN MONTH(@fecha) >= 9 AND MONTH(@fecha) <= 12 THEN 3
		END))
RETURN @id;
END
GO

------------------------------------------------------ CARGA DE LOS HECHOS ------------------------------------------------------

-- HECHOS INCIDENTES
INSERT INTO [COSMICOS].[BI_HECHOS_INCIDENTES] (CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, 
		CODIGO_TIEMPO, CODIGO_TIPO_INCIDENTE, CANTIDAD_INCIDENTES)
SELECT C.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA, 
		COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA) AS CODIGO_TIEMPO, TI.INCIDENTE_TIPO, COUNT(I.CODIGO_INCIDENTE)
FROM COSMICOS.CIRCUITO C 
	JOIN COSMICOS.SECTOR S ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
	JOIN COSMICOS.TIPO_SECTOR TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
	JOIN COSMICOS.INCIDENTE I ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
	JOIN COSMICOS.CARRERA CA ON I.CODIGO_CARRERA = CA.CODIGO_CARRERA
	JOIN COSMICOS.AUTO_POR_INCIDENTE AI ON AI.CODIGO_INCIDENTE = I.CODIGO_INCIDENTE
	JOIN COSMICOS.TIPO_INCIDENTE TI ON AI.TIPO_INCIDENTE = TI.INCIDENTE_TIPO
	JOIN COSMICOS.AUTO_POR_CARRERA AC ON AI.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
	JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
	JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
GROUP BY  C.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA, COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA), TI.INCIDENTE_TIPO


-- HECHOS PARADAS
INSERT INTO [COSMICOS].[BI_HECHOS_PARADAS] (CODIGO_CIRCUITO, CODIGO_ESCUDERIA, CODIGO_TIEMPO, CODIGO_TIPO_NEU_VIEJO, 
											CODIGO_TIPO_NEU_NUEVO, TIEMPO_PARADA, CANTIDAD_PARADAS)
SELECT CA.CIRCUITO_CODIGO, E.CODIGO_ESCUDERIA, COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA) AS CODIGO_TIEMPO,
		TN1.NEUMATICO_TIPO, TN2.NEUMATICO_TIPO,  SUM(PB.PARADA_BOX_TIEMPO), COUNT(PB.CODIGO_PARADA_BOX)
FROM COSMICOS.CARRERA CA 
	JOIN COSMICOS.AUTO_POR_CARRERA AC ON CA.CODIGO_CARRERA = AC.CODIGO_CARRERA
	JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
	JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
	JOIN COSMICOS.PARADA_BOX PB ON AC.CODIGO_AUTO_POR_CARRERA = PB.CODIGO_AUTO_POR_CARRERA
	
	JOIN COSMICOS.NEUMATICO_POR_PARADA NP1 ON NP1.CODIGO_PARADA_BOX = PB.CODIGO_PARADA_BOX AND NP1.TIPO = 'VIEJO'
	JOIN COSMICOS.NEUMATICO_POR_AUTO NA1 on NA1.CODIGO_NEUMATICO_POR_AUTO = NP1.CODIGO_NEUMATICO_POR_AUTO
	JOIN COSMICOS.NEUMATICO N1 on N1.NEUMATICO_NRO_SERIE = NA1.NEUMATICO_NRO_SERIE
	JOIN COSMICOS.TIPO_NEUMATICO TN1 on N1.NEUMATICO_TIPO = TN1.NEUMATICO_TIPO

	JOIN COSMICOS.NEUMATICO_POR_PARADA NP2 ON NP2.CODIGO_PARADA_BOX = PB.CODIGO_PARADA_BOX AND NP2.TIPO = 'NUEVO'
	JOIN COSMICOS.NEUMATICO_POR_AUTO NA2 on NA2.CODIGO_NEUMATICO_POR_AUTO = NP2.CODIGO_NEUMATICO_POR_AUTO
	JOIN COSMICOS.NEUMATICO N2 on N2.NEUMATICO_NRO_SERIE = NA2.NEUMATICO_NRO_SERIE
	JOIN COSMICOS.TIPO_NEUMATICO TN2 on N2.NEUMATICO_TIPO = TN2.NEUMATICO_TIPO
GROUP BY CA.CIRCUITO_CODIGO, E.CODIGO_ESCUDERIA, COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA), TN1.NEUMATICO_TIPO, TN2.NEUMATICO_TIPO
ORDER BY  E.CODIGO_ESCUDERIA


-- HECHOS AUTOS Y CARRERAS
INSERT INTO [COSMICOS].[BI_HECHOS_AUTOS_Y_CARRERAS] (CODIGO_VUELTA, CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, 
			CODIGO_PILOTO, CODIGO_TIEMPO, CONSUMO_COMBUSTIBLE, TIEMPO_VUELTA, MAXIMA_VELOCIDAD, CODIGO_AUTO, DESGASTE_NEUMATICO_1,
			DESGASTE_NEUMATICO_2, DESGASTE_NEUMATICO_3, DESGASTE_NEUMATICO_4, DESGASTE_FRENO_1, DESGASTE_FRENO_2, DESGASTE_FRENO_3,
			DESGASTE_FRENO_4, DESGASTE_MOTOR, DESGASTE_CAJA)
SELECT V.CODIGO_VUELTA, S.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA,
		P.CODIGO_PILOTO, COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA), AVG(T.TELE_AUTO_COMBUSTIBLE), MIN(T.TELE_AUTO_TIEMPO_VUELTA),
		MAX(T.TELE_AUTO_VELOCIDAD) AS MAX_VELOCIDAD, T.CODIGO_AUTO_POR_CARRERA,
		(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO1, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO2, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO3, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO4,
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO1, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO2, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO3, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO4,
	(SELECT (MAX(TELE_MOTOR_POTENCIA) - MIN(TELE_MOTOR_POTENCIA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_MOTOR TM1 ON T1.CODIGO_TELE_MOTOR = TM1.CODIGO_TELE_MOTOR
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND S1.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_MOTOR, 
	AVG (TC.TELE_CAJA_DESGASTE) AS DESGASTE_CAJA
FROM COSMICOS.TELEMETRIA T
	JOIN COSMICOS.TELEMETRIA_CAJA TC ON T.CODIGO_TELE_CAJA = TC.CODIGO_TELE_CAJA
	JOIN COSMICOS.AUTO_POR_CARRERA AC ON T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
	JOIN COSMICOS.SECTOR S ON T.CODIGO_SECTOR = S.CODIGO_SECTOR
	JOIN COSMICOS.TIPO_SECTOR TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
	JOIN COSMICOS.BI_DIMENSION_VUELTA V ON T.TELE_AUTO_NUMERO_VUELTA = V.NUMERO_VUELTA
	JOIN COSMICOS.CARRERA CA ON AC.CODIGO_CARRERA = CA.CODIGO_CARRERA
	JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
	JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
	JOIN COSMICOS.PILOTO P ON P.CODIGO_PILOTO = A.CODIGO_PILOTO
GROUP BY V.CODIGO_VUELTA, S.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA, P.CODIGO_PILOTO,
		COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA), --T.TELE_AUTO_COMBUSTIBLE, T.TELE_AUTO_TIEMPO_VUELTA,
		T.TELE_AUTO_NUMERO_VUELTA, T.CODIGO_AUTO_POR_CARRERA
ORDER BY V.CODIGO_VUELTA, S.CIRCUITO_CODIGO, E.CODIGO_ESCUDERIA

GO

------------------------------------------------------ VISTAS ------------------------------------------------------

-- Q1
-- Desgaste promedio de cada componente de cada auto por vuelta por circuito
CREATE VIEW COSMICOS.Desgastes_Por_Auto_Por_Vuelta_Por_Circuito AS
SELECT H.CODIGO_AUTO, V.NUMERO_VUELTA, H.CODIGO_CIRCUITO, C.CIRCUITO_NOMBRE, DESGASTE_NEUMATICO_1, DESGASTE_NEUMATICO_2,
DESGASTE_NEUMATICO_3, DESGASTE_NEUMATICO_4, DESGASTE_FRENO_1, DESGASTE_FRENO_2, DESGASTE_FRENO_3, DESGASTE_FRENO_4, DESGASTE_MOTOR, DESGASTE_CAJA
FROM COSMICOS.BI_HECHOS_AUTOS_Y_CARRERAS H
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON H.CODIGO_CIRCUITO = C.CIRCUITO_CODIGO
JOIN COSMICOS.BI_DIMENSION_VUELTA V ON H.CODIGO_VUELTA = V.CODIGO_VUELTA
GO

-- Q2

-- Q3
-- Los 3 de circuitos con mayor consumo de combustible promedio
CREATE VIEW COSMICOS.Circuitos_Mayor_Consumo AS
SELECT TOP 3 H.CODIGO_CIRCUITO, C.CIRCUITO_NOMBRE, MAX(H.CONSUMO_COMBUSTIBLE) MAYOR_CONSUMO_COMUSTIBLE
FROM COSMICOS.BI_HECHOS_AUTOS_Y_CARRERAS H
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON H.CODIGO_CIRCUITO = C.CIRCUITO_CODIGO
GROUP BY H.CODIGO_CIRCUITO, C.CIRCUITO_NOMBRE
ORDER BY MAYOR_CONSUMO_COMUSTIBLE
GO

-- Q4
-- Máxima velocidad alcanzada por cada auto en cada tipo de sector de cada circuito.
CREATE VIEW COSMICOS.Max_Velocidad_Por_Auto_Por_Sector_Por_Circuito  AS
SELECT A.CODIGO_AUTO,A.AUTO_NUMERO,A.AUTO_MODELO,S.DESCRIPCION,C.CIRCUITO_NOMBRE, MAX(H.MAXIMA_VELOCIDAD) MAX_VELOCIDAD
FROM COSMICOS.BI_HECHOS_AUTOS_Y_CARRERAS H
JOIN COSMICOS.BI_DIMENSION_AUTO A ON A.CODIGO_AUTO = H.CODIGO_AUTO
JOIN COSMICOS.BI_DIMENSION_TIPO_SECTOR S ON S.CODIGO_TIPO_SECTOR = H.CODIGO_TIPO_SECTOR
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON C.CIRCUITO_CODIGO = H.CODIGO_CIRCUITO
GROUP BY A.CODIGO_AUTO,A.AUTO_NUMERO,A.AUTO_MODELO ,S.DESCRIPCION,C.CIRCUITO_NOMBRE
GO

-- Q5
-- Tiempo promedio que tardó cada escudería en las paradas por cuatrimestre.
CREATE VIEW COSMICOS.Tiempo_Promedio_Parada_Por_Escuderia_Por_Cuatri AS
SELECT  E.ESCUDERIA_NOMBRE, DM.CUATRIMESTRE,DM.ANIO , SUM(P.TIEMPO_PARADA)/SUM(CANTIDAD_PARADAS) 'Promedio paradas'
FROM COSMICOS.BI_HECHOS_PARADAS P
JOIN COSMICOS.BI_DIMENSION_TIEMPO DM ON DM.CODIGO_TIEMPO = P.CODIGO_TIEMPO
JOIN COSMICOS.BI_DIMENSION_ESCUDERIA E ON E.CODIGO_ESCUDERIA = P.CODIGO_ESCUDERIA
GROUP BY E.ESCUDERIA_NOMBRE, DM.CUATRIMESTRE,DM.ANIO
GO

-- Q6
-- Cantidad de paradas por circuito por escudería por año.
CREATE VIEW COSMICOS.Cant_Paradas_Por_Circuito_Por_Escuderia_Por_Anio as
SELECT E.ESCUDERIA_NOMBRE,C.CIRCUITO_NOMBRE, DM.ANIO, SUM(P.CANTIDAD_PARADAS) 'Cantidad paradas' FROM COSMICOS.BI_HECHOS_PARADAS P
JOIN COSMICOS.BI_DIMENSION_TIEMPO DM ON DM.CODIGO_TIEMPO = P.CODIGO_TIEMPO
JOIN COSMICOS.BI_DIMENSION_ESCUDERIA E ON E.CODIGO_ESCUDERIA = P.CODIGO_ESCUDERIA
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON C.CIRCUITO_CODIGO = P.CODIGO_CIRCUITO
GROUP BY E.ESCUDERIA_NOMBRE,C.CIRCUITO_NOMBRE,DM.ANIO
GO

-- Q7
--Los 3 circuitos donde se consume mayor cantidad en tiempo de paradas en boxes. 
CREATE VIEW COSMICOS.Tiempo_Por_Parada_Por_Circuito AS
SELECT TOP 3 P.CODIGO_CIRCUITO, DI.CIRCUITO_NOMBRE, SUM(TIEMPO_PARADA) TIEMPO_PARADA
FROM COSMICOS.BI_HECHOS_PARADAS P
JOIN COSMICOS.BI_DIMENSION_CIRCUITO DI ON DI.CIRCUITO_CODIGO = P.CODIGO_CIRCUITO
GROUP BY P.CODIGO_CIRCUITO, DI.CIRCUITO_NOMBRE
ORDER BY SUM(TIEMPO_PARADA) DESC
GO

-- Q8
-- Los 3 circuitos más peligrosos del año, en función mayor cantidad de incidentes.
CREATE VIEW COSMICOS.Circuitos_Mas_Peligrosos_Por_Anio AS
SELECT TOP 3 I.CODIGO_CIRCUITO, C.CIRCUITO_NOMBRE, T.ANIO
FROM COSMICOS.BI_HECHOS_INCIDENTES I
JOIN COSMICOS.BI_DIMENSION_TIEMPO T ON T.CODIGO_TIEMPO = I.CODIGO_TIEMPO
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON C.CIRCUITO_CODIGO = I.CODIGO_CIRCUITO
GROUP BY  I.CODIGO_CIRCUITO, C.CIRCUITO_NOMBRE, T.ANIO
ORDER BY SUM(I.CANTIDAD_INCIDENTES)
GO

-- Q9
