------------------------------------------------------ CREACION DE LAS DIMENSIONES ------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_DIMENSION_CIRCUITO] (
	[CIRCUITO_CODIGO] int PRIMARY KEY,
	[CIRCUITO_NOMBRE] nvarchar(255),
	[CIRCUITO_PAIS] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_SECTOR] (
	[CODIGO_SECTOR] int PRIMARY KEY, 
	[SECTOR_DISTANCIA] decimal(18,2),
	[SECTOR_TIPO] nvarchar(255),
)
GO


CREATE TABLE [COSMICOS].[BI_DIMENSION_ESCUDERIA] (
	[CODIGO_ESCUDERIA] int PRIMARY KEY, 
	[ESCUDERIA_NOMBRE] varchar(50),
	[ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIEMPO](
	[CODIGO_TIEMPO] int PRIMARY KEY IDENTITY(1,1),
	[CUATRIMESTRE] int,
	[ANIO] int
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_INCIDENTE](
	[CODIGO_INCIDENTE] int PRIMARY KEY,
	[TIPO_INCIDENTE] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TELE](
	[CODIGO_TELE] int PRIMARY KEY,
	[NUMERO_VUELTA] decimal(18,0),
	[TIEMPO_VUELTA] decimal(18,10)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_COMPONENTES](
	[CODIGO_COMPONENTE] int PRIMARY KEY IDENTITY(1,1),
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_AUTO] (
	[CODIGO_AUTO] int  PRIMARY KEY,
	[AUTO_NUMERO] int,
	[AUTO_MODELO] nvarchar(255)
)
GO


-------------------------------------------------------- CREACION DE LOS HECHOS ------------------------------------------------------

CREATE TABLE [COSMICOS].[HECHOS_AUTOS_Y_CARRERAS] (
	[CODIGO_TELE] int REFERENCES [COSMICOS].[BI_DIMENSION_TELE],
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_COMPONENTE] int REFERENCES [COSMICOS].[BI_DIMENSION_COMPONENTES],
	[DESGASTE_COMPONENTE] decimal (18,6),
	[CONSUMO_COMBUSTIBLE] decimal (18,2),
	[MAXIMA_VELOCIDAD] decimal (18,2),
	CONSTRAINT PK_HECHOS_AUTOS_Y_CARRERAS PRIMARY KEY (CODIGO_TELE, CODIGO_CIRCUITO, CODIGO_SECTOR, CODIGO_ESCUDERIA, CODIGO_COMPONENTE)
)
GO

CREATE TABLE [COSMICOS].[HECHOS_INCIDENTES] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[CODIGO_INCIDENTE] int REFERENCES [COSMICOS].[BI_DIMENSION_INCIDENTE] ,
	[CANTIDAD INCIDENTES] int,
	CONSTRAINT PK_HECHOS_INCIDENTES PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_SECTOR, CODIGO_ESCUDERIA, CODIGO_TIEMPO, CODIGO_INCIDENTE)
)
GO

CREATE TABLE [COSMICOS].[HECHOS_PARADAS] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[TIEMPO_PARADA] decimal(18,2),
	[CANTIDAD_PARADAS] int,
	CONSTRAINT PK_HECHOS_PARADAS PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_ESCUDERIA, CODIGO_TIEMPO)
)
GO


------------------------------------------------------ CARGA DE LAS DIMENSIONES ------------------------------------------------------

 -- TOMADO DE LAS FECHAS DE CARRERA, QUE SE SUPONEN QUE SON LAS QUE EXISTEN
 INSERT INTO [COSMICOS].[BI_DIMENSION_TIEMPO] (CUATRIMESTRE, ANIO) 
 SELECT DISTINCT (CASE  
	WHEN MONTH(CARRERA_FECHA) >= 1 AND MONTH(CARRERA_FECHA) <= 4 THEN 1
	WHEN MONTH(CARRERA_FECHA) >= 5 AND MONTH(CARRERA_FECHA) <= 8 THEN 2
	WHEN MONTH(CARRERA_FECHA) >= 9 AND MONTH(CARRERA_FECHA) <= 12 THEN 3
	end) ,YEAR(CARRERA_FECHA)FROM COSMICOS.CARRERA

------------------------------------------------------ CARGA DE LOS HECHOS ------------------------------------------------------



------------------------------------------------------ VISTAS ------------------------------------------------------


-- Q1
-- Q2
-- Q3
-- Q4
-- Q5
-- Q6
-- Q7
-- Q8
-- Q9
