------------------------------------------------------ CREACION DE LAS DIMENSIONES ------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_DIMENSION_CIRCUITO] (
	[CIRCUITO_CODIGO] int PRIMARY KEY,
	[CIRCUITO_NOMBRE] nvarchar(255),
	[CIRCUITO_PAIS] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_SECTOR] (
	[CODIGO_TIPO_SECTOR] int PRIMARY KEY, 
	[DESCRIPCION] nvarchar(255),
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_ESCUDERIA] (
	[CODIGO_ESCUDERIA] int PRIMARY KEY, 
	[ESCUDERIA_NOMBRE] varchar(50),
	[ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIEMPO](
	[CODIGO_TIEMPO] int PRIMARY KEY IDENTITY(1,1),
	[CUATRIMESTRE] int,
	[ANIO] int
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE](
	[CODIGO_TIPO_INCIDENTE] int PRIMARY KEY,
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO](
	[CODIGO_TIPO_NEUMATICO] int PRIMARY KEY,
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_VUELTA](
	[CODIGO_VUELTA] int PRIMARY KEY IDENTITY(1,1),
	[NUMERO_VUELTA] decimal(18,0)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_COMPONENTES](
	[CODIGO_COMPONENTE] int PRIMARY KEY IDENTITY(1,1),
	[DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_AUTO] (
	[CODIGO_AUTO] int  PRIMARY KEY,
	[AUTO_NUMERO] int,
	[AUTO_MODELO] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_PILOTO] (
  [CODIGO_PILOTO] int PRIMARY KEY,
  [PILOTO_NOMBRE] varchar(50),
  [PILOTO_APELLIDO] varchar(50),
  [PILOTO_NACIONALIDAD] varchar(50)
)
GO

-------------------------------------------------------- CREACION DE LOS HECHOS ------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_HECHOS_AUTOS_Y_CARRERAS] (
	[CODIGO_VUELTA] int REFERENCES [COSMICOS].[BI_DIMENSION_VUELTA],
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_TIPO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_COMPONENTE] int REFERENCES [COSMICOS].[BI_DIMENSION_COMPONENTES],
	[CODIGO_TIPO_NEUMATICO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO],
	[CODIGO_PILOTO] int REFERENCES [COSMICOS].[BI_DIMENSION_PILOTO],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[DESGASTE_COMPONENTE] decimal (18,6),
	[CONSUMO_COMBUSTIBLE] decimal (18,2),
	[MAXIMA_VELOCIDAD] decimal (18,2),
	[MEJOR_TIEMPO] decimal (18,10),
	CONSTRAINT PK_HECHOS_AUTOS_Y_CARRERAS PRIMARY KEY (CODIGO_VUELTA, CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, 
	CODIGO_COMPONENTE, CODIGO_TIPO_NEUMATICO, CODIGO_PILOTO, CODIGO_TIEMPO)
)
GO

CREATE TABLE [COSMICOS].[BI_HECHOS_INCIDENTES] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_TIPO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_SECTOR],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[CODIGO_TIPO_INCIDENTE] int REFERENCES [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE],
	[CANTIDAD_INCIDENTES] int,
	CONSTRAINT PK_HECHOS_INCIDENTES PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, CODIGO_TIEMPO, CODIGO_TIPO_INCIDENTE)
)
GO

CREATE TABLE [COSMICOS].[BI_HECHOS_PARADAS] (
	[CODIGO_CIRCUITO] int REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA],
	[CODIGO_TIEMPO] int REFERENCES [COSMICOS].[BI_DIMENSION_TIEMPO],
	[TIEMPO_PARADA] decimal(18,2),
	[CANTIDAD_PARADAS] int,
	CONSTRAINT PK_HECHOS_PARADAS PRIMARY KEY (CODIGO_CIRCUITO, CODIGO_ESCUDERIA, CODIGO_TIEMPO)
)
GO


------------------------------------------------------ CARGA DE LAS DIMENSIONES ------------------------------------------------------

-- DIMENSION CIRCUITO
INSERT INTO [COSMICOS].[BI_DIMENSION_CIRCUITO] 
SELECT
  CIRCUITO_CODIGO,
  CIRCUITO_NOMBRE,
  CIRCUITO_PAIS 
FROM COSMICOS.CIRCUITO

-- DIMENSION TIPO SECTOR
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_SECTOR] 
SELECT
  SECTOR_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_SECTOR

-- DIMENSION ESCUDERIA
INSERT INTO [COSMICOS].[BI_DIMENSION_ESCUDERIA] 
SELECT
  CODIGO_ESCUDERIA, 
  ESCUDERIA_NOMBRE,
  ESCUDERIA_NACIONALIDAD
FROM COSMICOS.ESCUDERIA

-- DIMENSION TIEMPO
-- TOMADO DE LAS FECHAS DE CARRERA, QUE SE SUPONEN QUE SON LAS QUE EXISTEN
INSERT INTO [COSMICOS].[BI_DIMENSION_TIEMPO] (CUATRIMESTRE, ANIO) 
SELECT DISTINCT (CASE  
	WHEN MONTH(CARRERA_FECHA) >= 1 AND MONTH(CARRERA_FECHA) <= 4 THEN 1
	WHEN MONTH(CARRERA_FECHA) >= 5 AND MONTH(CARRERA_FECHA) <= 8 THEN 2
	WHEN MONTH(CARRERA_FECHA) >= 9 AND MONTH(CARRERA_FECHA) <= 12 THEN 3
	end) ,YEAR(CARRERA_FECHA)
FROM COSMICOS.CARRERA

-- DIMENSION TIPO INCIDENTE
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_INCIDENTE]  
SELECT
  INCIDENTE_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_INCIDENTE 

-- DIMENSION TIPO NEUMATICO
INSERT INTO [COSMICOS].[BI_DIMENSION_TIPO_NEUMATICO]  
SELECT
  NEUMATICO_TIPO,
  DESCRIPCION
FROM COSMICOS.TIPO_NEUMATICO 

-- DIMENSION COMPONENTES
INSERT INTO [COSMICOS].[BI_DIMENSION_COMPONENTES]
VALUES
	('NEUMATICO_1'),
	('NEUMATICO_2'),
	('NEUMATICO_3'),
	('NEUMATICO_4'),
	('FRENO_1'),
	('FRENO_2'),
	('FRENO_3'),
	('FRENO_4'),
	('MOTOR'),
	('CAJA')
	
-- DIMENSION AUTO
INSERT INTO [COSMICOS].[BI_DIMENSION_AUTO]  
SELECT
  AC.CODIGO_AUTO_POR_CARRERA,
  AUTO_NUMERO,
  AUTO_MODELO 
FROM COSMICOS.AUTO A
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = A.CODIGO_AUTO

-- DIMENSION PILOTO
INSERT INTO [COSMICOS].[BI_DIMENSION_PILOTO]
SELECT 
	CODIGO_PILOTO,
	PILOTO_NOMBRE,
	PILOTO_APELLIDO, 
	PILOTO_NACIONALIDAD
FROM COSMICOS.PILOTO

-- DIMENSION VUELTA
INSERT INTO [COSMICOS].[BI_DIMENSION_VUELTA]
SELECT DISTINCT 
	TELE_AUTO_NUMERO_VUELTA
FROM COSMICOS.TELEMETRIA
ORDER BY TELE_AUTO_NUMERO_VUELTA
GO

------------------------------------------------------ FUNCIONES AUXILIARES ------------------------------------------------------

CREATE FUNCTION COSMICOS.PK_Del_Tiempo (@fecha datetime)
RETURNS INT
AS
BEGIN
DECLARE @id INT;
	SET @id = (SELECT CODIGO_TIEMPO FROM BI_DIMENSION_TIEMPO
	WHERE ANIO = YEAR(@fecha) AND CUATRIMESTRE = (CASE  
		WHEN MONTH(@fecha) >= 1 AND MONTH(@fecha) <= 4 THEN 1
		WHEN MONTH(@fecha) >= 5 AND MONTH(@fecha) <= 8 THEN 2
		WHEN MONTH(@fecha) >= 9 AND MONTH(@fecha) <= 12 THEN 3
		END))
RETURN @id;
END
GO

------------------------------------------------------ CARGA DE LOS HECHOS ------------------------------------------------------

--INSERT INTO [COSMICOS].[BI_HECHOS_AUTOS_Y_CARRERAS] (CODIGO_VUELTA, CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, 
--			CODIGO_COMPONENTE, CODIGO_TIPO_NEUMATICO, CODIGO_PILOTO, CODIGO_TIEMPO, DESGASTE_COMPONENTE, 
--			CONSUMO_COMBUSTIBLE, MAXIMA_VELOCIDAD, MEJOR_TIEMPO)

-- HECHOS INCIDENTES
INSERT INTO [COSMICOS].[BI_HECHOS_INCIDENTES] (CODIGO_CIRCUITO, CODIGO_TIPO_SECTOR, CODIGO_ESCUDERIA, 
		CODIGO_TIEMPO, CODIGO_TIPO_INCIDENTE, CANTIDAD_INCIDENTES)
SELECT C.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA, 
		COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA) AS CODIGO_TIEMPO, TI.INCIDENTE_TIPO, COUNT(I.CODIGO_INCIDENTE)
FROM COSMICOS.CIRCUITO C 
	JOIN COSMICOS.SECTOR S ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
	JOIN COSMICOS.TIPO_SECTOR TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
	JOIN COSMICOS.INCIDENTE I ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
	JOIN COSMICOS.CARRERA CA ON I.CODIGO_CARRERA = CA.CODIGO_CARRERA
	JOIN COSMICOS.AUTO_POR_INCIDENTE AI ON AI.CODIGO_INCIDENTE = I.CODIGO_INCIDENTE
	JOIN COSMICOS.TIPO_INCIDENTE TI ON AI.TIPO_INCIDENTE = TI.INCIDENTE_TIPO
	JOIN COSMICOS.AUTO_POR_CARRERA AC ON AI.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
	JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
	JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
GROUP BY  C.CIRCUITO_CODIGO, TS.SECTOR_TIPO, E.CODIGO_ESCUDERIA, COSMICOS.PK_Del_Tiempo(CA.CARRERA_FECHA), TI.INCIDENTE_TIPO


------------------------------------------------------ VISTAS ------------------------------------------------------


-- Q1
-- Q2
-- Q3
-- Q4
-- Q5
-- Q6
-- Q7
-- Q8
-- Q9
