-- PRIMER TABLA DE SCRIPT. CIRCUITO
INSERT INTO COSMICOS.CIRCUITO (CIRCUITO_CODIGO, CIRCUITO_NOMBRE,CIRCUITO_PAIS)
SELECT distinct CIRCUITO_CODIGO, CIRCUITO_NOMBRE,CIRCUITO_PAIS 
FROM gd_esquema.Maestra 
order by CIRCUITO_CODIGO

-- CARRERA
INSERT INTO COSMICOS.CARRERA (CODIGO_CARRERA, 
CIRCUITO_CODIGO,
CARRERA_FECHA,
CARRERA_CLIMA,
CARRERA_TOTAL_CARRERA,
CARRERA_CANT_VUELTAS)
SELECT DISTINCT 
CODIGO_CARRERA, 
CIRCUITO_CODIGO,
CARRERA_FECHA,
CARRERA_CLIMA,
CARRERA_TOTAL_CARRERA,
CARRERA_CANT_VUELTAS
FROM gd_esquema.Maestra

--TIPO SECTOR
INSERT INTO COSMICOS.TIPO_SECTOR (DESCRIPCION)
SELECT  DISTINCT  SECTO_TIPO
FROM gd_esquema.Maestra 

--SECTOR
INSERT INTO COSMICOS.SECTOR (CODIGO_SECTOR, SECTRO_DISTANCIA, SECTOR_TIPO, CIRCUITO_CODIGO)
SELECT DISTINCT CODIGO_SECTOR, SECTOR_DISTANCIA, ts.SECTO_TIPO, CIRCUITO_CODIGO
FROM gd_esquema.Maestra m
JOIN COSMICOS.TIPO_SECTOR ts ON m.SECTOR_TIPO = ts.DESCRIPCION
