
--BEGIN TRAN PRUEBA

-- TELEMETRIA MOTOR
INSERT INTO COSMICOS.TELEMETRIA_MOTOR (TELE_MOTOR_NRO_SERIE, TELE_MOTOR_POTENCIA, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM)
SELECT DISTINCT TELE_MOTOR_NRO_SERIE, TELE_MOTOR_POTENCIA, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM 
from gd_esquema.Maestra m
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL

--SELECT * FROM COSMICOS.TELEMETRIA_MOTOR
--SELECT * FROM COSMICOS.MOTOR

--TELEMETRIA_CAJA 
INSERT INTO COSMICOS.TELEMETRIA_CAJA (TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE )
SELECT DISTINCT TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE 
from gd_esquema.Maestra m
WHERE TELE_CAJA_NRO_SERIE IS NOT NULL


-- TELEMETRIA
-- tiene mas pinta, devuelve 218.641 rows
SELECT TELE_AUTO_CODIGO, TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_POSICION,
TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_VELOCIDAD,
TELE_AUTO_COMBUSTIBLE, tc.CODIGO_TELE_CAJA, tm.CODIGO_TELE_MOTOR,
CODIGO_CARRERA, CODIGO_SECTOR, au.CODIGO_AUTO
from gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA_CAJA TC ON M.TELE_CAJA_NRO_SERIE = TC.TELE_CAJA_NRO_SERIE 
		AND M.TELE_CAJA_TEMP_ACEITE = TC.TELE_CAJA_TEMP_ACEITE AND M.TELE_CAJA_RPM = TC.TELE_CAJA_RPM 
		AND M.TELE_CAJA_DESGASTE = TC.TELE_CAJA_DESGASTE
JOIN COSMICOS.TELEMETRIA_MOTOR  TM ON M.TELE_MOTOR_NRO_SERIE = TM.TELE_MOTOR_NRO_SERIE 
		AND M.TELE_MOTOR_POTENCIA = TM.TELE_MOTOR_POTENCIA AND M.TELE_MOTOR_TEMP_ACEITE = TM.TELE_MOTOR_TEMP_ACEITE
		AND M.TELE_MOTOR_TEMP_AGUA = TM.TELE_MOTOR_TEMP_AGUA AND M.TELE_MOTOR_RPM = TM.TELE_MOTOR_RPM
JOIN COSMICOS.AUTO AU on AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
		AND AU.MOTOR_NRO_SERIE = M.TELE_MOTOR_NRO_SERIE
		AND AU.CAJA_NRO_SERIE = M.TELE_CAJA_NRO_SERIE
 
 -- TELEMETRIA FRENO
 -- algo no cierra porque para algunas telemetrias hay 24 frenos medidos
 Insert cosmicos.TELEMETRIA_FRENO (TELE_FRENO_NRO_SERIE,  TELE_FRENO_GROSOR_PASTILLA, TELE_FRENO_TEMPERATURA, CODIGO_TELE )
 SELECT TELE_FRENO1_NRO_SERIE,TELE_FRENO1_GROSOR_PASTILLA,TELE_FRENO1_TEMPERATURA, T.CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_FRENO2_NRO_SERIE,TELE_FRENO2_GROSOR_PASTILLA,TELE_FRENO2_TEMPERATURA, T.CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_FRENO3_NRO_SERIE,TELE_FRENO3_GROSOR_PASTILLA,TELE_FRENO3_TEMPERATURA, T.CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_FRENO4_NRO_SERIE,TELE_FRENO4_GROSOR_PASTILLA,TELE_FRENO4_TEMPERATURA, T.CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
--SELECT * FROM COSMICOS.AUTO


-- TELEMETRIA NEUMATICO
-- algo no cierra porque para algunas telemetrias hay 24 neumaticos medidos
INSERT COSMICOS.TELEMETRIA_NEUMATICO(TELE_NEUMATICO_NRO_SERIE, TELE_NEUMATICO_PRESION, TELE_NEUMATICO_PROFUNDIDAD, TELE_NEUMATICO_TEMPERATURA,CODIGO_TELE)
SELECT TELE_NEUMATICO1_NRO_SERIE, TELE_NEUMATICO1_PRESION,TELE_NEUMATICO1_PROFUNDIDAD, TELE_NEUMATICO1_TEMPERATURA, CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_NEUMATICO2_NRO_SERIE, TELE_NEUMATICO2_PRESION,TELE_NEUMATICO2_PROFUNDIDAD, TELE_NEUMATICO2_TEMPERATURA, CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_NEUMATICO3_NRO_SERIE, TELE_NEUMATICO3_PRESION,TELE_NEUMATICO3_PROFUNDIDAD, TELE_NEUMATICO3_TEMPERATURA, CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
 UNION
 SELECT TELE_NEUMATICO4_NRO_SERIE, TELE_NEUMATICO4_PRESION,TELE_NEUMATICO4_PROFUNDIDAD, TELE_NEUMATICO4_TEMPERATURA, CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
ORDER BY 5

