-- TELEMETRIA MOTOR
INSERT INTO COSMICOS.TELEMETRIA_MOTOR (TELE_MOTOR_NRO_SERIE, TELE_MOTOR_POTENCIA, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM)
SELECT DISTINCT TELE_MOTOR_NRO_SERIE, TELE_MOTOR_POTENCIA, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM 
from gd_esquema.Maestra
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL


--TELEMETRIA_CAJA 
INSERT INTO COSMICOS.TELEMETRIA_CAJA (TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE)
SELECT DISTINCT TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE 
from gd_esquema.Maestra
WHERE TELE_CAJA_NRO_SERIE IS NOT NULL


-- TELEMETRIA
-- Hay 218.641 telemetrias
INSERT INTO COSMICOS.TELEMETRIA (CODIGO_TELE, CODIGO_AUTO_POR_CARRERA, CODIGO_CARRERA, CODIGO_SECTOR,
TELE_AUTO_DISTANCIA_CARRERA, TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_TIEMPO_VUELTA, TELE_AUTO_POSICION, TELE_AUTO_VELOCIDAD, 
TELE_AUTO_NUMERO_VUELTA, TELE_AUTO_COMBUSTIBLE, CODIGO_TELE_MOTOR, CODIGO_TELE_CAJA)
SELECT DISTINCT TELE_AUTO_CODIGO, AC.CODIGO_AUTO_POR_CARRERA, M.CODIGO_CARRERA, CODIGO_SECTOR, 
TELE_AUTO_DISTANCIA_CARRERA, TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_TIEMPO_VUELTA, TELE_AUTO_POSICION, TELE_AUTO_VELOCIDAD,
TELE_AUTO_NUMERO_VUELTA, TELE_AUTO_COMBUSTIBLE, TM.CODIGO_TELE_MOTOR, TC.CODIGO_TELE_CAJA
from gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA_CAJA TC ON M.TELE_CAJA_NRO_SERIE = TC.TELE_CAJA_NRO_SERIE 
		AND M.TELE_CAJA_TEMP_ACEITE = TC.TELE_CAJA_TEMP_ACEITE AND M.TELE_CAJA_RPM = TC.TELE_CAJA_RPM 
		AND M.TELE_CAJA_DESGASTE = TC.TELE_CAJA_DESGASTE
JOIN COSMICOS.TELEMETRIA_MOTOR  TM ON M.TELE_MOTOR_NRO_SERIE = TM.TELE_MOTOR_NRO_SERIE 
		AND M.TELE_MOTOR_POTENCIA = TM.TELE_MOTOR_POTENCIA AND M.TELE_MOTOR_TEMP_ACEITE = TM.TELE_MOTOR_TEMP_ACEITE
		AND M.TELE_MOTOR_TEMP_AGUA = TM.TELE_MOTOR_TEMP_AGUA AND M.TELE_MOTOR_RPM = TM.TELE_MOTOR_RPM
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
		AND AC.MOTOR_NRO_SERIE = M.TELE_MOTOR_NRO_SERIE
		AND AC.CAJA_NRO_SERIE = M.TELE_CAJA_NRO_SERIE
ORDER BY TELE_AUTO_CODIGO
 

 -- TELEMETRIA FRENO
 -- Por cada tlemetria general, hay 4 mediciones de frenos
 -- Hay 874.564 telemetrias de frenos, que es igual a cantidad de telemetrias * 4
INSERT INTO COSMICOS.TELEMETRIA_FRENO (TELE_FRENO_NRO_SERIE, TELE_FRENO_GROSOR_PASTILLA, TELE_FRENO_TEMPERATURA, CODIGO_TELE)
SELECT TELE_FRENO1_NRO_SERIE, TELE_FRENO1_GROSOR_PASTILLA, TELE_FRENO1_TEMPERATURA, T.CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_FRENO2_NRO_SERIE, TELE_FRENO2_GROSOR_PASTILLA, TELE_FRENO2_TEMPERATURA, T.CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_FRENO3_NRO_SERIE, TELE_FRENO3_GROSOR_PASTILLA, TELE_FRENO3_TEMPERATURA, T.CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_FRENO4_NRO_SERIE, TELE_FRENO4_GROSOR_PASTILLA, TELE_FRENO4_TEMPERATURA, T.CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON  T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
ORDER BY 4 



-- TELEMETRIA NEUMATICO
-- Por cada telemetria general, hay 4 mediciones de neumaticos, misma cantidad de registros que el freno
INSERT COSMICOS.TELEMETRIA_NEUMATICO (TELE_NEUMATICO_NRO_SERIE, TELE_NEUMATICO_PRESION, TELE_NEUMATICO_PROFUNDIDAD, TELE_NEUMATICO_TEMPERATURA, CODIGO_TELE)
SELECT TELE_NEUMATICO1_NRO_SERIE, TELE_NEUMATICO1_PRESION, TELE_NEUMATICO1_PROFUNDIDAD, TELE_NEUMATICO1_TEMPERATURA, CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_NEUMATICO2_NRO_SERIE, TELE_NEUMATICO2_PRESION, TELE_NEUMATICO2_PROFUNDIDAD, TELE_NEUMATICO2_TEMPERATURA, CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_NEUMATICO3_NRO_SERIE, TELE_NEUMATICO3_PRESION, TELE_NEUMATICO3_PROFUNDIDAD, TELE_NEUMATICO3_TEMPERATURA, CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
UNION
SELECT TELE_NEUMATICO4_NRO_SERIE, TELE_NEUMATICO4_PRESION, TELE_NEUMATICO4_PROFUNDIDAD, TELE_NEUMATICO4_TEMPERATURA, CODIGO_TELE
FROM gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA T ON T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
	AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
	AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
	AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
	AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
	AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE
JOIN COSMICOS.AUTO AU ON AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO 
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO = AU.CODIGO_AUTO 
	AND M.CODIGO_CARRERA = AC.CODIGO_CARRERA
	AND T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
ORDER BY 5
