
--BEGIN TRAN PRUEBA

-- TELEMETRIA MOTOR
INSERT INTO COSMICOS.TELEMETRIA_MOTOR
SELECT DISTINCT TELE_MOTOR_NRO_SERIE, TELE_MOTOR_POTENCIA, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_RPM 
from gd_esquema.Maestra m
WHERE TELE_MOTOR_NRO_SERIE IS NOT NULL

--SELECT * FROM COSMICOS.TELEMETRIA_MOTOR
--SELECT * FROM COSMICOS.MOTOR

--TELEMETRIA_CAJA 
INSERT INTO COSMICOS.TELEMETRIA_CAJA (TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE )
SELECT DISTINCT TELE_CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE 
from gd_esquema.Maestra m
WHERE TELE_CAJA_NRO_SERIE IS NOT NULL

--ROLLBACK

--SELECT * FROM COSMICOS.TELEMETRIA_CAJA

--SELECT DISTINCT  FRENO_NRO_SERIE
--from gd_esquema.Maestra m


-- TELEMETRIA
/*************************** NO CARGA, SI PONER TOP SI CARGA *****************/
--TELE_AUTO_NUMERO_VUELTA,
--TELE_AUTO_NUMERO_VUELTA,
--DISTINCT

INSERT INTO COSMICOS.TELEMETRIA
( TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_POSICION,
TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_VELOCIDAD,
TELE_AUTO_COMBUSTIBLE, CODIGO_TELE_CAJA,CODIGO_TELE_MOTOR,
CODIGO_CARRERA, CODIGO_SECTOR,CODIGO_AUTO)
SELECT TOP 5000 TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_POSICION,
TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_VELOCIDAD,
TELE_AUTO_COMBUSTIBLE, CODIGO_TELE_CAJA,CODIGO_TELE_MOTOR,
CODIGO_CARRERA, CODIGO_SECTOR,CODIGO_AUTO
from gd_esquema.Maestra M
JOIN COSMICOS.TELEMETRIA_CAJA as TC ON M.TELE_CAJA_NRO_SERIE = TC.TELE_CAJA_NRO_SERIE
JOIN COSMICOS.TELEMETRIA_MOTOR as TM ON M.TELE_MOTOR_NRO_SERIE = TM.TELE_MOTOR_NRO_SERIE
JOIN COSMICOS.AUTO AS AU on AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO

SELECT DISTINCT TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_DISTANCIA_CARRERA,TELE_AUTO_POSICION,
TELE_AUTO_TIEMPO_VUELTA,TELE_AUTO_VELOCIDAD,
TELE_AUTO_COMBUSTIBLE, CODIGO_TELE_CAJA,CODIGO_TELE_MOTOR,
CODIGO_CARRERA, CODIGO_SECTOR,CODIGO_AUTO
FROM gd_esquema.Maestra M, COSMICOS.TELEMETRIA_CAJA AS TC, COSMICOS.TELEMETRIA_MOTOR AS TM, COSMICOS.AUTO AU
WHERE M.TELE_CAJA_NRO_SERIE = TC.TELE_CAJA_NRO_SERIE
AND M.TELE_MOTOR_NRO_SERIE = TM.TELE_MOTOR_NRO_SERIE
AND AU.AUTO_MODELO = M.AUTO_MODELO AND AU.AUTO_NUMERO = M.AUTO_NUMERO

-- NO ESTAN TERMINADAS PORQUE NO TERMINA DE ANDAR BIEN TELEMETRIA PARA PROBARLAS. 
 
 -- TELEMETRIA FRENO
 SELECT TELE_FRENO1_NRO_SERIE,TELE_FRENO1_POSICION,TELE_FRENO1_TAMANIO_DISCO,TELE_FRENO1_TEMPERATURA, T.CODIGO_TELE
 FROM gd_esquema.Maestra as M
 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE

--SELECT * FROM COSMICOS.AUTO


-- TELEMETRIA NEUMATICO
SELECT DISTINCT TELE_NEUMATICO1_NRO_SERIE, TELE_NEUMATICO1_PRESION,TELE_NEUMATICO1_PROFUNDIDAD,
TELE_NEUMATICO1_TEMPERATURA, CODIGO_TELE
 FROM gd_esquema.Maestra as M

 JOIN COSMICOS.Telemetria as T on 
 T.TELE_AUTO_DISTANCIA_CARRERA = M.TELE_AUTO_DISTANCIA_CARRERA 
 AND T.TELE_AUTO_DISTANCIA_VUELTA = M.TELE_AUTO_DISTANCIA_VUELTA
 AND T.TELE_AUTO_POSICION = M.TELE_AUTO_POSICION
 AND T.TELE_AUTO_TIEMPO_VUELTA = M.TELE_AUTO_TIEMPO_VUELTA
 AND T.TELE_AUTO_VELOCIDAD  = M.TELE_AUTO_VELOCIDAD
 AND T.TELE_AUTO_COMBUSTIBLE = M.TELE_AUTO_COMBUSTIBLE


-- SELECT * FROM COSMICOS.TELEMETRIA
  --WHERE TELE_NEUMATICO1_NRO_SERIE IS NOT NULL
