-- PRIMER TABLA DE SCRIPT. CIRCUITO
INSERT INTO COSMICOS.CIRCUITO (CIRCUITO_CODIGO, CIRCUITO_NOMBRE,CIRCUITO_PAIS)
SELECT distinct CIRCUITO_CODIGO, CIRCUITO_NOMBRE,CIRCUITO_PAIS 
FROM gd_esquema.Maestra 
order by CIRCUITO_CODIGO

-- CARRERA
INSERT INTO COSMICOS.CARRERA (CODIGO_CARRERA, 
CIRCUITO_CODIGO,
CARRERA_FECHA,
CARRERA_CLIMA,
CARRERA_TOTAL_CARRERA,
CARRERA_CANT_VUELTAS)
SELECT DISTINCT 
CODIGO_CARRERA, 
CIRCUITO_CODIGO,
CARRERA_FECHA,
CARRERA_CLIMA,
CARRERA_TOTAL_CARRERA,
CARRERA_CANT_VUELTAS
FROM gd_esquema.Maestra

--TIPO SECTOR
insert into COSMICOS.TIPO_SECTOR (SECTOR_TIPO )
select  DISTINCT  SECTO_TIPO
FROM gd_esquema.Maestra 

--SECTOR
insert into COSMICOS.SECTOR (CODIGO_SECTOR, SECTRO_DISTANCIA, SECTOR_TIPO, CIRCUITO_CODIGO)
select DISTINCT CODIGO_SECTOR, SECTOR_DISTANCIA, SECTO_TIPO, CIRCUITO_CODIGO
from gd_esquema.Maestra
