CREATE TABLE [CIRCUITO] (
  [CIRCUITO_CODIGO] int PRIMARY KEY,
  [CIRCUITO_NOMBRE] nvarchar(255),
  [CIRCUITO_PAIS] nvarchar(255)
)
GO

CREATE TABLE [CARRERA] (
  [CODIGO_CARRERA] int PRIMARY KEY,
  [CARRERA_FECHA] date,
  [CARRERA_CLIMA] nvarchar(100),
  [CARRERA_TOTAL_CARRERA] decimal(18,2),
  [CARRERA_CANT_VUELTAS] int,
  [CIRCUITO_CODIGO] int NOT NULL
)
GO

CREATE TABLE [TIPO_SECTOR] (
  [SECTOR_TIPO] int PRIMARY KEY IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [SECTOR] (
  [CODIGO_SECTOR] int PRIMARY KEY,
  [SECTRO_DISTANCIA] decimal(18,2),
  [SECTOR_TIPO] int,
  [CIRCUITO_CODIGO] int NOT NULL
)
GO

CREATE TABLE [PILOTO] (
  [CODIGO_PILOTO] int PRIMARY KEY,
  [PILOTO_NOMBRE] varchar(50),
  [PILOTO_APELLIDO] varchar(50),
  [PILOTO_NACIONALIDAD] varchar(50),
  [PILOTO_FECHA_NACIMIENTO] datetime
)
GO

CREATE TABLE [ESCUDERIA] (
  [CODIGO_ESCUDERIA] int PRIMARY KEY,
  [ESCUDERIA_NOMBRE] varchar(50),
  [ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [MOTOR] (
  [MOTOR_NRO_SERIE] nvarchar(255) PRIMARY KEY,
  [MOTOR_MODELO] nvarchar(255)
)
GO

CREATE TABLE [CAJA] (
  [CAJA_NRO_SERIE] nvarchar(255) PRIMARY KEY,
  [CAJA_MODELO] nvarchar(255)
)
GO

CREATE TABLE [FRENO] (
  [FRENO_NRO_SERIE] nvarchar(255) PRIMARY KEY,
  [FRENO_POSICION] nvarchar(255),
  [FRENO_TAMANIO_DISCO] decimal(18, 2)
)
GO

CREATE TABLE [TIPO_NEUMATICO] (
  [NEUMATICO_TIPO] int PRIMARY KEY IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [NEUMATICO] (
  [NEUMATICO_NRO_SERIE] nvarchar(255) PRIMARY KEY,
  [NEUMATICO_POSICION] nvarchar(255),
  [NEUMATICO_TIPO] int
)
GO

CREATE TABLE [AUTO] (
  [AUTO_NUMERO] int PRIMARY KEY,
  [AUTO_MODELO] Nvarchar(255),
  [CODIGO_PILOTO] int NOT NULL,
  [CODIGO_ESCUDERIA] int NOT NULL,
  [MOTOR] nvarchar(255) NOT NULL,
  [CAJA_NRO_SERIE] nvarchar(255) NOT NULL
)
GO

CREATE TABLE [NEUMATICO_POR_AUTO] (
  [CODIGO_NEUMATICO_POR_AUTO] int IDENTITY(1, 1),
  [NEUMATICO_NRO_SERIE] nvarchar(255),
  [AUTO_NUMERO] int,
  [ACTIVO] bit,
  PRIMARY KEY ([CODIGO_NEUMATICO_POR_AUTO], [NEUMATICO_NRO_SERIE])
)
GO

CREATE TABLE [FRENO_POR_AUTO] (
  [CODIGO_FRENO_POR_AUTO] int IDENTITY(1, 1),
  [FRENO_NRO_SERIE] nvarchar(255),
  [AUTO_NUMERO] int NOT NULL,
  [ACTIVO] bit,
  PRIMARY KEY ([CODIGO_FRENO_POR_AUTO], [FRENO_NRO_SERIE])
)
GO

CREATE TABLE [BANDERA] (
  [CODIGO_BANDERA] int PRIMARY KEY IDENTITY(1, 1),
  [COMPORTAMIENTO] nvarchar(255)
)
GO

CREATE TABLE [TIPO_INCIDENTE] (
  [INCIDENTE_TIPO] int PRIMARY KEY IDENTITY(1, 1),
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [INCIDENTE] (
  [CODIGO_INCIDENTE] int PRIMARY KEY IDENTITY(1, 1),
  [CODIGO_CARRERA] int NOT NULL,
  [CODIGO_SECTOR] int NOT NULL,
  [CODIGO_BANDERA] int,
  [INCIDENTE_TIEMPO] decimal(18, 2)
)
GO

CREATE TABLE [AUTO_POR_INCIDENTE] (
  [CODIGO_AUTO_POR_INCIDENTE] int PRIMARY KEY IDENTITY(1, 1),
  [CODIGO_INCIDENTE] int NOT NULL,
  [AUTO_NUMERO] int NOT NULL,
  [TIPO_INCIDENTE] int NOT NULL,
  [NRO_VUELTA] decimal(18, 0) NOT NULL
)
GO

CREATE TABLE [PARADA_BOX] (
  [CODIGO_PARADA_BOX] int PRIMARY KEY IDENTITY(1, 1),
  [CODIGO_CARRERA] int NOT NULL,
  [AUTO_NUMERO] int NOT NULL,
  [PARADA_BOX_VUELTA] decimal(18, 0),
  [PARADA_BOX_TIEMPO] decimal(18, 2)
)
GO

CREATE TABLE [NEUMATICO_POR_PARADA] (
  [CODIGO_NEUMATICO_POR_PARADA] int IDENTITY(1, 1),
  [CODIGO_NEUMATICO_POR_AUTO] int,
  [CODIGO_PARADA_BOX] int NOT NULL,
  [TIPO] nvarchar(255) NOT NULL CHECK ([TIPO] IN ('VIEJO', 'NUEVO')),
  PRIMARY KEY ([CODIGO_NEUMATICO_POR_PARADA], [CODIGO_NEUMATICO_POR_AUTO])
)
GO

CREATE TABLE [TELEMETRIA_MOTOR] (
  [CODIGO_TELE_MOTOR] int PRIMARY KEY IDENTITY(1, 1),
  [TELE_MOTOR_NRO_SERIE] nvarchar(255) NOT NULL,
  [TELE_MOTOR_POTENCIA] decimal(18, 6),
  [TELE_MOTOR_TEMP_ACEITE] decimal(18, 6),
  [TELE_MOTOR_TEMP_AGUA] decimal(18, 6),
  [TELE_MOTOR_RPM] decimal(18, 6)
)
GO

CREATE TABLE [TELEMETRIA_CAJA] (
  [CODIGO_TELE_CAJA] int PRIMARY KEY IDENTITY(1, 1),
  [TELE_CAJA_NRO_SERIE] nvarchar(255) NOT NULL,
  [TELE_CAJA_TEMP_ACEITE] decimal(18, 2),
  [TELE_CAJA_RPM] decimal(18, 2),
  [TELE_CAJA_DESGASTE] decimal(18, 2)
)
GO

CREATE TABLE [TELEMETRIA_NEUMATICO] (
  [CODIGO_TELE_NEUMATICO] int PRIMARY KEY IDENTITY(1, 1),
  [TELE_NEUMATICO_NRO_SERIE] nvarchar(255) NOT NULL,
  [CODIGO_TELE] int NOT NULL,
  [TELE_NEUMATICO_PRESION] decimal(18, 6),
  [TELE_NEUMATICO_PROFUNDIDAD] decimal(18, 6),
  [TELE_NEUMATICO_TEMPERATURA] decimal(18, 6)
)
GO

CREATE TABLE [TELEMETRIA_FRENO] (
  [CODIGO_TELE_FRENO] int PRIMARY KEY IDENTITY(1, 1),
  [TELE_FRENO_NRO_SERIE] nvarchar(255) NOT NULL,
  [CODIGO_TELE] int NOT NULL,
  [TELE_FRENO_TEMPERATURA] decimal(18, 2),
  [TELE_FRENO_GROSOR_PASTILLA] decimal(18, 2)
)
GO

CREATE TABLE [TELEMETRIA] (
  [CODIGO_TELE] int PRIMARY KEY IDENTITY(1, 1),
  [AUTO_NUMERO] decimal(18, 0) NOT NULL,
  [CODIGO_CARRERA] int NOT NULL,
  [CODIGO_SECTOR] int NOT NULL,
  [TELE_AUTO_NUMERO_VUELTA] decimal(18, 0),
  [TELE_AUTO_DISTANCIA_CARRERA] decimal(18, 6),
  [TELE_AUTO_DISTANCIA_VUELTA] decimal(18, 2),
  [TELE_AUTO_TIEMPO_VUELTA] decimal(18, 10),
  [TELE_AUTO_POSICION] decimal(18, 0),
  [TELE_AUTO_VELOCIDAD] decimal(18, 2),
  [TELE_AUTO_COMBUSTIBLE] decimal(18, 2),
  [CODIGO_TELE_MOTOR] int NOT NULL,
  [CODIGO_TELE_CAJA] int NOT NULL
)
GO

ALTER TABLE [CARRERA] ADD FOREIGN KEY ([CIRCUITO_CODIGO]) REFERENCES [CIRCUITO] ([CIRCUITO_CODIGO])
GO

ALTER TABLE [SECTOR] ADD FOREIGN KEY ([CIRCUITO_CODIGO]) REFERENCES [CIRCUITO] ([CIRCUITO_CODIGO])
GO

ALTER TABLE [SECTOR] ADD FOREIGN KEY ([SECTOR_TIPO]) REFERENCES [TIPO_SECTOR] ([SECTOR_TIPO])
GO

ALTER TABLE [NEUMATICO] ADD FOREIGN KEY ([NEUMATICO_TIPO]) REFERENCES [TIPO_NEUMATICO] ([NEUMATICO_TIPO])
GO

ALTER TABLE [PILOTO] ADD FOREIGN KEY ([CODIGO_PILOTO]) REFERENCES [AUTO] ([CODIGO_PILOTO])
GO

ALTER TABLE [ESCUDERIA] ADD FOREIGN KEY ([CODIGO_ESCUDERIA]) REFERENCES [AUTO] ([CODIGO_ESCUDERIA])
GO

ALTER TABLE [MOTOR] ADD FOREIGN KEY ([MOTOR_NRO_SERIE]) REFERENCES [AUTO] ([MOTOR])
GO

ALTER TABLE [CAJA] ADD FOREIGN KEY ([CAJA_NRO_SERIE]) REFERENCES [AUTO] ([CAJA_NRO_SERIE])
GO

ALTER TABLE [NEUMATICO_POR_AUTO] ADD FOREIGN KEY ([NEUMATICO_NRO_SERIE]) REFERENCES [NEUMATICO] ([NEUMATICO_NRO_SERIE])
GO

ALTER TABLE [NEUMATICO_POR_AUTO] ADD FOREIGN KEY ([AUTO_NUMERO]) REFERENCES [AUTO] ([AUTO_NUMERO])
GO

ALTER TABLE [FRENO_POR_AUTO] ADD FOREIGN KEY ([FRENO_NRO_SERIE]) REFERENCES [FRENO] ([FRENO_NRO_SERIE])
GO

ALTER TABLE [FRENO_POR_AUTO] ADD FOREIGN KEY ([AUTO_NUMERO]) REFERENCES [AUTO] ([AUTO_NUMERO])
GO

ALTER TABLE [INCIDENTE] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [INCIDENTE] ADD FOREIGN KEY ([CODIGO_SECTOR]) REFERENCES [SECTOR] ([CODIGO_SECTOR])
GO

ALTER TABLE [INCIDENTE] ADD FOREIGN KEY ([CODIGO_BANDERA]) REFERENCES [BANDERA] ([CODIGO_BANDERA])
GO

ALTER TABLE [AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([CODIGO_INCIDENTE]) REFERENCES [INCIDENTE] ([CODIGO_INCIDENTE])
GO

ALTER TABLE [AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([AUTO_NUMERO]) REFERENCES [AUTO] ([AUTO_NUMERO])
GO

ALTER TABLE [AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([TIPO_INCIDENTE]) REFERENCES [TIPO_INCIDENTE] ([INCIDENTE_TIPO])
GO

ALTER TABLE [PARADA_BOX] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [PARADA_BOX] ADD FOREIGN KEY ([AUTO_NUMERO]) REFERENCES [AUTO] ([AUTO_NUMERO])
GO

ALTER TABLE [NEUMATICO_POR_PARADA] ADD FOREIGN KEY ([CODIGO_NEUMATICO_POR_AUTO]) REFERENCES [NEUMATICO_POR_AUTO] ([CODIGO_NEUMATICO_POR_AUTO])
GO

ALTER TABLE [NEUMATICO_POR_PARADA] ADD FOREIGN KEY ([CODIGO_PARADA_BOX]) REFERENCES [PARADA_BOX] ([CODIGO_PARADA_BOX])
GO

ALTER TABLE [TELEMETRIA_MOTOR] ADD FOREIGN KEY ([TELE_MOTOR_NRO_SERIE]) REFERENCES [MOTOR] ([MOTOR_NRO_SERIE])
GO

ALTER TABLE [TELEMETRIA_CAJA] ADD FOREIGN KEY ([TELE_CAJA_NRO_SERIE]) REFERENCES [CAJA] ([CAJA_NRO_SERIE])
GO

ALTER TABLE [TELEMETRIA_NEUMATICO] ADD FOREIGN KEY ([TELE_NEUMATICO_NRO_SERIE]) REFERENCES [NEUMATICO] ([NEUMATICO_NRO_SERIE])
GO

ALTER TABLE [TELEMETRIA_NEUMATICO] ADD FOREIGN KEY ([CODIGO_TELE]) REFERENCES [TELEMETRIA] ([CODIGO_TELE])
GO

ALTER TABLE [TELEMETRIA_FRENO] ADD FOREIGN KEY ([TELE_FRENO_NRO_SERIE]) REFERENCES [FRENO] ([FRENO_NRO_SERIE])
GO

ALTER TABLE [TELEMETRIA_FRENO] ADD FOREIGN KEY ([CODIGO_TELE]) REFERENCES [TELEMETRIA] ([CODIGO_TELE])
GO

ALTER TABLE [TELEMETRIA] ADD FOREIGN KEY ([AUTO_NUMERO]) REFERENCES [AUTO] ([AUTO_NUMERO])
GO

ALTER TABLE [TELEMETRIA] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [TELEMETRIA] ADD FOREIGN KEY ([CODIGO_SECTOR]) REFERENCES [SECTOR] ([CODIGO_SECTOR])
GO

ALTER TABLE [TELEMETRIA] ADD FOREIGN KEY ([CODIGO_TELE_MOTOR]) REFERENCES [TELEMETRIA_MOTOR] ([CODIGO_TELE_MOTOR])
GO

ALTER TABLE [TELEMETRIA] ADD FOREIGN KEY ([CODIGO_TELE_CAJA]) REFERENCES [TELEMETRIA_CAJA] ([CODIGO_TELE_CAJA])
GO
