-- OPCION 1
SELECT AC.CODIGO_AUTO,TS.DESCRIPCION,C.CIRCUITO_CODIGO
,MAX(TELE_AUTO_VELOCIDAD) "Maxima velocidad Alcanzada" from COSMICOS.TELEMETRIA as T
JOIN COSMICOS.SECTOR as S on S.CODIGO_SECTOR = T.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO as C on C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
JOIN COSMICOS.TIPO_SECTOR as TS on TS.SECTOR_TIPO = S.SECTOR_TIPO
JOIN COSMICOS.AUTO_POR_CARRERA as AC on AC.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
GROUP BY AC.CODIGO_AUTO,TS.DESCRIPCION,C.CIRCUITO_CODIGO
ORDER BY 1,2
-- TOMAMOS QUE UN AUTO ES UNICO POR SU CODIGO DE AUTO. 

--OPCION 2
SELECT T.CODIGO_AUTO_POR_CARRERA,TS.DESCRIPCION,C.CIRCUITO_CODIGO
,MAX(TELE_AUTO_VELOCIDAD) "Maxima velocidad Alcanzada" from COSMICOS.TELEMETRIA as T
JOIN COSMICOS.SECTOR as S on S.CODIGO_SECTOR = T.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO as C on C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
JOIN COSMICOS.TIPO_SECTOR as TS on TS.SECTOR_TIPO = S.SECTOR_TIPO
GROUP BY CODIGO_AUTO_POR_CARRERA,TS.DESCRIPCION,C.CIRCUITO_CODIGO
ORDER BY 1,2
-- TOMAMOS QUE UN AUTO ES UNICO POR EL CODIGO AUTO POR CARRERA.  
