--Los 3 circuitos más peligrosos del año, en función mayor cantidad de incidentes. 

SELECT C2.CIRCUITO_CODIGO ------------------------------------------------------------------------------PRUEBA
FROM [COSMICOS].[CIRCUITO] C2
JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
WHERE YEAR(CAR.CARRERA_FECHA) = YEAR(GETDATE())--- SI ES DEL AÑO ACTUAL

--------------------------------------------------------------------------------------------------------------

create view v_circuitos_mas_peligrosos(
CODIGO_CIRCUITO , NOMBRE , INCIDENTES_POR_CIRCUITO) AS
select top 3  C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE,COUNT(CODIGO_INCIDENTE) 
FROM [COSMICOS].[CIRCUITO] C 
JOIN [COSMICOS].[SECTOR] S ON C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
LEFT JOIN [COSMICOS].[INCIDENTE] I ON S.CODIGO_SECTOR = I.CODIGO_SECTOR where C.CIRCUITO_CODIGO in(
SELECT C2.CIRCUITO_CODIGO 
FROM [COSMICOS].[CIRCUITO] C2
JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
WHERE YEAR(CAR.CARRERA_FECHA) = YEAR(GETDATE()))
GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE


SELECT * FROM V_CIRCUITOS_MAS_PELIGROSOS


DROP PROCEDURE TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO

CREATE procedure TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO (@anio smallint)--- prcedure que devuelve el top 3 por año parametrizado YAPA??	
as
begin
	select top 3  C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, C.CIRCUITO_PAIS, COUNT(CODIGO_INCIDENTE) AS INCIDENTES_POR_CIRCUITO
FROM [COSMICOS].[CIRCUITO] C 
JOIN [COSMICOS].[SECTOR] S ON C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
LEFT JOIN [COSMICOS].[INCIDENTE] I ON S.CODIGO_SECTOR = I.CODIGO_SECTOR where C.CIRCUITO_CODIGO in(
SELECT C2.CIRCUITO_CODIGO 
FROM [COSMICOS].[CIRCUITO] C2
JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
WHERE YEAR(CAR.CARRERA_FECHA) = @anio)
GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, C.CIRCUITO_PAIS
ORDER BY COUNT(CODIGO_INCIDENTE) DESC
end

exec TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO 2020

-----------------------------------------------------------------------------------------------------------------------------------------

--Promedio de incidentes que presenta cada escudería por año en los distintos tipo de sectores.


SELECT *FROM [COSMICOS].[INCIDENTE]

SELECT *  FROM [COSMICOS].[SECTOR]

--Promedio de incidentes que presenta cada escudería por año en los distintos tipo de sectores.

SELECT E.CODIGO_ESCUDERIA,[DESCRIPCION],YEAR(CARRERA_FECHA) AÑO, AVG(I.CODIGO_INCIDENTE) PROMEDIO_INCIDENTES 
FROM [COSMICOS].[ESCUDERIA] E 
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA) -- DEBERIA SACAAR EL PROMERDIO POR AÑO DE EL SECTORES EN CARRERAS CORRIDAS POR AUTOS DE  UNA ECUDERIA



--INCIDENTES POR AÑO EN CADA SECTOR POR ESCUDERIA
SELECT E.CODIGO_ESCUDERIA,[DESCRIPCION],YEAR(CARRERA_FECHA), COUNT(I.CODIGO_INCIDENTE) FROM [COSMICOS].[ESCUDERIA] E 
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA)

SELECT DESCRIPCION FROM [COSMICOS].[TIPO_SECTOR]  TS JOIN [COSMICOS].[SECTOR] S ON TS.DESCRIPCION = S.SECTOR_TIPO -- ME CHACE RUIDOOO!!

--incidentes por ecuderia en tipo de sectores

SELECT E.CODIGO_ESCUDERIA,[DESCRIPCION], COUNT(I.CODIGO_INCIDENTE) FROM [COSMICOS].[ESCUDERIA] E 
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION

-- incidentes por ecuderia
SELECT E.CODIGO_ESCUDERIA, COUNT(I.CODIGO_INCIDENTE) FROM [COSMICOS].[ESCUDERIA] E 
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
GROUP BY E.CODIGO_ESCUDERIA

