--TOP 3 CIRCUITOS MAS PELIGROSOS DEL AÑO

create view v_circuitos_mas_peligrosos_por_año(
CODIGO_CIRCUITO , NOMBRE , INCIDENTES_POR_CIRCUITO) AS
select top 3  C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, COUNT(CODIGO_INCIDENTE) 
FROM [COSMICOS].[CIRCUITO] C 
JOIN [COSMICOS].[SECTOR] S ON C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
LEFT JOIN [COSMICOS].[INCIDENTE] I ON S.CODIGO_SECTOR = I.CODIGO_SECTOR where C.CIRCUITO_CODIGO in(
SELECT C2.CIRCUITO_CODIGO 
FROM [COSMICOS].[CIRCUITO] C2
JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
WHERE YEAR(CAR.CARRERA_FECHA) = YEAR(GETDATE()))
GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE

select * from v_circuitos_mas_peligrosos_por_año


DROP PROCEDURE TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO

CREATE procedure TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO (@anio smallint)--- prcedure que devuelve el top 3 por año parametrizado YAPA??	
as
begin
	select top 3  C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, C.CIRCUITO_PAIS, COUNT(CODIGO_INCIDENTE) AS INCIDENTES_POR_CIRCUITO
FROM [COSMICOS].[CIRCUITO] C 
JOIN [COSMICOS].[SECTOR] S ON C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
LEFT JOIN [COSMICOS].[INCIDENTE] I ON S.CODIGO_SECTOR = I.CODIGO_SECTOR where C.CIRCUITO_CODIGO in(
SELECT C2.CIRCUITO_CODIGO 
FROM [COSMICOS].[CIRCUITO] C2
JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
WHERE YEAR(CAR.CARRERA_FECHA) = @anio)
GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, C.CIRCUITO_PAIS
ORDER BY COUNT(CODIGO_INCIDENTE) DESC
end

exec TOP_3_CIRCUITOS_MAS_PELIGROSOS_POR_AÑO 2020

SELECT * FROM COSMICOS.INCIDENTE
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- PROMEDIO DE INCIDENTES QUE PRESENTA CADA ESCUDERIA POR AÑO EN LOS DISTINTOS TIPOS DE SECTORES

SELECT DISTINCT E.CODIGO_ESCUDERIA, DESCRIPCION,YEAR(CARRERA_FECHA) AÑO, count(I.CODIGO_INCIDENTE) CANTIDAD-- CANTIDAD_INCIDENTES / cantidad de incidentes en los tipos de sectores
FROM [COSMICOS].[ESCUDERIA] E																	  -- MUESTTRA EL CANTIDAD POR TIPO DE SECTOR
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA)


-------------------------------------------------------------------------------
select * from V_PROMEDIO_DE_INCIDENTES_ESCUDERIA_POR_TIPO_DE_SECTOR
DROP VIEW  V_PROMEDIO_DE_INCIDENTES_ESCUDERIA_POR_TIPO_DE_SECTOR

CREATE VIEW V_PROMEDIO_DE_INCIDENTES_ESCUDERIA_POR_TIPO_DE_SECTOR(
 CODIGO_ESCUDERIA, DESCRIPCION, AÑO, CANTIDAD
 )
 AS
SELECT E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA) AÑO, (count(I.CODIGO_INCIDENTE)/COUNT(s.[CODIGO_SECTOR])) PROMEDIO   --PROMEDIO_INCIDENTES / SI HUBIERA MAS CASOS DARIA EL PROMEDIO
FROM [COSMICOS].[ESCUDERIA] E																									 --MUESTTRA EL PROMDEDIO POR TIPO DE SECTOR
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA)

CREATE VIEW V_PROMEDIO_DE_INCIDENTES_ESCUDERIA_POR_SECTORES(
 CODIGO_ESCUDERIA, DESCRIPCION, AÑO, CANTIDAD
 )
 AS
SELECT E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA) AÑO, (count(I.CODIGO_INCIDENTE)/COUNT(TS.SECTOR_TIPO)) PROMEDIO      --PROMEDIO_INCIDENTES / SI HUBIERA MAS CASOS DARIA EL PROMEDIO
FROM [COSMICOS].[ESCUDERIA] E																									 -- MUESTTRA EL PROMDEDIO POR TODOS LOS TIPOS DE SECTORES
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA																 --NO HAY SUFICIENTES EJEMPLOS EN LA BASE PARA OBSERVAR UN RESULTADO CONVINCENTE
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN [COSMICOS].[TIPO_SECTOR] TS ON S.SECTOR_TIPO = TS.SECTOR_TIPO
GROUP BY E.CODIGO_ESCUDERIA, DESCRIPCION, YEAR(CARRERA_FECHA)