--CREACION DE TABLAS-----------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE [COSMICOS].[BI_DIMENSION_CIRCUITO] (
  [CIRCUITO_CODIGO] int PRIMARY KEY,
  [CIRCUITO_NOMBRE] nvarchar(255),
 )
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_SECTOR] (
  [CODIGO_SECTOR] int PRIMARY KEY, 
  [SECTOR_DISTANCIA] decimal(18,2),
  [SECTOR_TIPO] nvarchar(255),
 
)
GO


CREATE TABLE [COSMICOS].[BI_DIMENSION_ESCUDERIA] (
  [CODIGO_ESCUDERIA] int PRIMARY KEY, 
  [ESCUDERIA_NOMBRE] varchar(50),
  --[ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [COSMICOS].[BI_DIMENSION_AUTO] (
  [CODIGO_AUTO] int  PRIMARY KEY,
  [AUTO_NUMERO] int NOT NULL,
  --[AUTO_MODELO] nvarchar(255),
  [CODIGO_PILOTO] int NOT NULL,
  [CODIGO_ESCUDERIA] int NOT NULL,
  -- DE AUTO X CARRERA
  [MOTOR_NRO_SERIE] nvarchar(255) NULL,
  [CAJA_NRO_SERIE] nvarchar(255) NULL,
)
GO

CREATE TABLE [COSMICOS].[BI_HechosPrincipal](
	[hecho_id] int PRIMARY KEY IDENTITY(1, 1),
	 [CODIGO_AUTO] int REFERENCES [COSMICOS].[BI_DIMENSION_AUTO] ,
	 [CODIGO_ESCUDERIA] int REFERENCES [COSMICOS].[BI_DIMENSION_ESCUDERIA] ,
	 [CIRCUITO_CODIGO] int  REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	 [CODIGO_SECTOR] int REFERENCES [COSMICOS].[BI_DIMENSION_SECTOR] ,
	 [Q2_MejorTiempoVuelta_XEscuderia_XCircuito_Xanio] decimal(18,10) null,
	 [Q3_Prom_Consumo_Combustible_XCircuito] decimal(18,2) null,
	 [Q4_Max_Velocidad_XAuto_XSector_XCircuito] decimal(18,2) null,
	 [Q5_Tiempo_Prom_XEscuderia_Xanio_XSector] decimal(18,10) null,
	 [Q6_Cant_Paradas_XCirc_Xanio_XEscuderia] int null,
	 [Q7_Tiempo_XParada_XCircuito] decimal(18,10) null,
	 [Q8_Cant_Incidente_XCircuito_XAnio] int null,
	 [Anio] int,
	 [Cuatrimestre] int

)
go
-- faltan las FK
CREATE TABLE [COSMICOS].[BI_HechosNeumaticos](
	[ID_HECHO_NEU] INT PRIMARY KEY IDENTITY(1, 1) ,
	[CODIGO_AUTO] int REFERENCES [COSMICOS].[BI_DIMENSION_AUTO],
	[CIRCUITO_CODIGO] int  REFERENCES [COSMICOS].[BI_DIMENSION_CIRCUITO],
	[NUMERO_VUELTA] int null ,
	[AUTO_COMBUSTIBLE] decimal(18,6) null,
	[DESGASTE_MOTOR] decimal(18,6) null,
	[DESGASTE_CAJA] decimal(18,6) null,
	[DESGASTE_NEUMATICO_1] decimal(18,6) null,
	[DESGASTE_NEUMATICO_2] decimal(18,6) null,
	[DESGASTE_NEUMATICO_3] decimal(18,6) null,
	[DESGASTE_NEUMATICO_4] decimal(18,6) null,
	[DESGASTE_FRENO_1] decimal(18,2) null,
	[DESGASTE_FRENO_2] decimal(18,2) null,
	[DESGASTE_FRENO_3] decimal(18,2) null,
	[DESGASTE_FRENO_4] decimal(18,2) null
)



--INSERT EN LAS DIMENSIONES-----------------------------------------------------------------------------------------------------------------------------------------------
--dimension_escuderia

INSERT INTO[COSMICOS].[BI_DIMENSION_ESCUDERIA] SELECT
  [CODIGO_ESCUDERIA] , 
  [ESCUDERIA_NOMBRE] 
FROM [COSMICOS].[ESCUDERIA]

--dimension_auto
INSERT INTO [COSMICOS].[BI_DIMENSION_AUTO]  SELECT
  AC.[CODIGO_AUTO_POR_CARRERA], 
  [AUTO_NUMERO] ,
  [CODIGO_PILOTO] ,
  [CODIGO_ESCUDERIA] ,
  [MOTOR_NRO_SERIE],
  [CAJA_NRO_SERIE] 
  FROM [COSMICOS].[AUTO] A
  JOIN [COSMICOS].[AUTO_POR_CARRERA] AC ON AC.CODIGO_AUTO = A.CODIGO_AUTO 

--dimension_circuito
INSERT INTO [COSMICOS].[BI_DIMENSION_CIRCUITO] SELECT
  [CIRCUITO_CODIGO] ,
  [CIRCUITO_NOMBRE] 
  FROM [COSMICOS].[CIRCUITO]

--dimension_sector
INSERT INTO [COSMICOS].[BI_DIMENSION_SECTOR] SELECT
  [CODIGO_SECTOR] , 
  [SECTOR_DISTANCIA] ,
  [DESCRIPCION]
FROM [COSMICOS].[SECTOR] S 
LEFT JOIN  [COSMICOS].[TIPO_SECTOR] T ON S.SECTOR_TIPO = T.SECTOR_TIPO


--INSERT EN LOS HECHOS-----------------------------------------------------------------------------------------------------------------------------------------------
--Q1

INSERT INTO COSMICOS.BI_HechosNeumaticos (CODIGO_AUTO, NUMERO_VUELTA, CIRCUITO_CODIGO, DESGASTE_NEUMATICO_1, DESGASTE_NEUMATICO_2,
DESGASTE_NEUMATICO_3, DESGASTE_NEUMATICO_4, DESGASTE_FRENO_1, DESGASTE_FRENO_2, DESGASTE_FRENO_3, DESGASTE_FRENO_4, DESGASTE_MOTOR, DESGASTE_CAJA) 
SELECT AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO,
		(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO1, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO2, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO3, 
	(SELECT (MAX(TELE_NEUMATICO_PROFUNDIDAD) - MIN(TELE_NEUMATICO_PROFUNDIDAD))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_NEUMATICO TN1 ON T1.CODIGO_TELE = TN1.CODIGO_TELE
		JOIN COSMICOS.NEUMATICO N1 ON TN1.TELE_NEUMATICO_NRO_SERIE = N1.NEUMATICO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND N1.NEUMATICO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_NEUMATICO4,
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO1, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Delantero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO2, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Derecho'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO3, 
	(SELECT (MAX(TELE_FRENO_GROSOR_PASTILLA) - MIN(TELE_FRENO_GROSOR_PASTILLA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_FRENO TF1 ON T1.CODIGO_TELE = TF1.CODIGO_TELE
		JOIN COSMICOS.FRENO F1 ON TF1.TELE_FRENO_NRO_SERIE = F1.FRENO_NRO_SERIE
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
			AND F1.FRENO_POSICION = 'Trasero Izquierdo'
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_FRENO4,
	(SELECT (MAX(TELE_MOTOR_POTENCIA) - MIN(TELE_MOTOR_POTENCIA))
		FROM COSMICOS.TELEMETRIA T1
		JOIN COSMICOS.TELEMETRIA_MOTOR TM1 ON T1.CODIGO_TELE_MOTOR = TM1.CODIGO_TELE_MOTOR
		JOIN COSMICOS.SECTOR S1 ON T1.CODIGO_SECTOR = S1.CODIGO_SECTOR
		JOIN COSMICOS.CIRCUITO C1 ON S1.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		WHERE 
			T1.TELE_AUTO_NUMERO_VUELTA = T.TELE_AUTO_NUMERO_VUELTA
			AND C1.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
			AND T1.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
		GROUP BY T1.CODIGO_AUTO_POR_CARRERA, T1.TELE_AUTO_NUMERO_VUELTA
	) AS DESGASTE_MOTOR, 
	AVG (TC.TELE_CAJA_DESGASTE) AS DESGASTE_CAJA
FROM COSMICOS.TELEMETRIA T
JOIN COSMICOS.TELEMETRIA_CAJA TC ON T.CODIGO_TELE_CAJA = TC.CODIGO_TELE_CAJA
JOIN COSMICOS.AUTO_POR_CARRERA AC ON T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
JOIN COSMICOS.SECTOR S ON T.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO C ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
GROUP BY T.CODIGO_AUTO_POR_CARRERA, AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO
ORDER BY AC.CODIGO_AUTO, T.TELE_AUTO_NUMERO_VUELTA, C.CIRCUITO_CODIGO


--Q2
--Mejor tiempo de vuelta de cada escudería por circuito por año. 

--listop
insert into COSMICOS.BI_HechosPrincipal (Q2_MejorTiempoVuelta_XEscuderia_XCircuito_Xanio,Anio ,CODIGO_AUTO, CODIGO_ESCUDERIA, CIRCUITO_CODIGO) 
select TELE_AUTO_TIEMPO_VUELTA , year(C.CARRERA_FECHA) as AÑO_CARRERA , A.CODIGO_AUTO, E.CODIGO_ESCUDERIA, C.CIRCUITO_CODIGO
from cosmicos.TELEMETRIA T
join COSMICOS.AUTO_POR_CARRERA AC on T.CODIGO_AUTO_POR_CARRERA = AC.CODIGO_AUTO_POR_CARRERA
join COSMICOS.AUTO A on A.CODIGO_AUTO = AC.CODIGO_AUTO
join COSMICOS.ESCUDERIA E on E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA
join COSMICOS.CARRERA C on C.CODIGO_CARRERA = AC.CODIGO_CARRERA
where TELE_AUTO_TIEMPO_VUELTA <> 0  and  TELE_AUTO_TIEMPO_VUELTA = (
		select top 1 TELE_AUTO_TIEMPO_VUELTA from COSMICOS.TELEMETRIA T1
		join COSMICOS.CARRERA C1 on C1.CODIGO_CARRERA = T1.CODIGO_CARRERA
		join COSMICOS.AUTO_POR_CARRERA AC1 on T1.CODIGO_AUTO_POR_CARRERA = AC1.CODIGO_AUTO_POR_CARRERA
		join COSMICOS.AUTO A1 on A1.CODIGO_AUTO = AC1.CODIGO_AUTO
		join COSMICOS.ESCUDERIA E1 on E1.CODIGO_ESCUDERIA = A1.CODIGO_ESCUDERIA and E1.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
		where  year(C.CARRERA_FECHA) = year(C1.CARRERA_FECHA) and   TELE_AUTO_TIEMPO_VUELTA <> 0 and C.CIRCUITO_CODIGO = C1.CIRCUITO_CODIGO
		group by  t1.TELE_AUTO_TIEMPO_VUELTA ,c1.CODIGO_CARRERA
		order by  t1.TELE_AUTO_TIEMPO_VUELTA 
		)	
order by CODIGO_ESCUDERIA,  AÑO_CARRERA,TELE_AUTO_TIEMPO_VUELTA 

--Q3
--Los 3 de circuitos con mayor consumo de combustible promedio. 
insert into COSMICOS.BI_HechosPrincipal (CIRCUITO_CODIGO, Q3_Prom_Consumo_Combustible_XCircuito) 
SELECT C.CIRCUITO_CODIGO, AVG(T.TELE_AUTO_COMBUSTIBLE)
FROM COSMICOS.TELEMETRIA T
JOIN COSMICOS.SECTOR S ON T.CODIGO_SECTOR = S.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO C ON S.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
GROUP BY C.CIRCUITO_CODIGO


--Q4
--Máxima velocidad alcanzada por cada auto en cada tipo de sector de cada circuito. 
insert into Cosmicos.BI_HechosPrincipal (CODIGO_AUTO,CODIGO_SECTOR,CIRCUITO_CODIGO,Q4_Max_Velocidad_XAuto_XSector_XCircuito) 
(SELECT AC.CODIGO_AUTO,TS.SECTOR_TIPO,C.CIRCUITO_CODIGO ,MAX(TELE_AUTO_VELOCIDAD)  from COSMICOS.TELEMETRIA as T
JOIN COSMICOS.SECTOR as S on S.CODIGO_SECTOR = T.CODIGO_SECTOR
JOIN COSMICOS.CIRCUITO as C on C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
JOIN COSMICOS.TIPO_SECTOR as TS on TS.SECTOR_TIPO = S.SECTOR_TIPO
JOIN COSMICOS.AUTO_POR_CARRERA as AC on AC.CODIGO_AUTO_POR_CARRERA = T.CODIGO_AUTO_POR_CARRERA
GROUP BY AC.CODIGO_AUTO,TS.SECTOR_TIPO ,C.CIRCUITO_CODIGO)


--Q5
--Tiempo promedio que tardó cada escudería en las paradas por cuatrimestre. 
INSERT INTO Cosmicos.BI_HechosPrincipal (CODIGO_ESCUDERIA,Q5_Tiempo_Prom_XEscuderia_Xanio_XSector,Cuatrimestre,Anio)

(SELECT E.CODIGO_ESCUDERIA,AVG(PARADA_BOX_TIEMPO) "Promedio", CASE  
	WHEN MONTH(CR.CARRERA_FECHA) >= 1 AND MONTH(CARRERA_FECHA) <= 4 THEN 1
	WHEN MONTH(CR.CARRERA_FECHA) >= 5 AND MONTH(CARRERA_FECHA) <= 8 THEN 2
	WHEN MONTH(CR.CARRERA_FECHA) >= 9 AND MONTH(CARRERA_FECHA) <= 12 THEN 3
	end AS "Cuatrimestre",YEAR(CR.CARRERA_FECHA) as "ANIO"
	 FROM COSMICOS.PARADA_BOX PB
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO_POR_CARRERA =  PB.CODIGO_AUTO_POR_CARRERA
JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
JOIN COSMICOS.CARRERA CR ON AC.CODIGO_CARRERA = CR.CODIGO_CARRERA
GROUP BY E.CODIGO_ESCUDERIA,CASE  
	WHEN MONTH(CR.CARRERA_FECHA) >= 1 AND MONTH(CARRERA_FECHA) <= 4 THEN 1
	WHEN MONTH(CR.CARRERA_FECHA) >= 5 AND MONTH(CARRERA_FECHA) <= 8 THEN 2
	WHEN MONTH(CR.CARRERA_FECHA) >= 9 AND MONTH(CARRERA_FECHA) <= 12 THEN 3
	end,YEAR(CR.CARRERA_FECHA)
	)
	
--Q6
--Cantidad de paradas por circuito por escudería por año. 

INSERT INTO Cosmicos.BI_HechosPrincipal (CIRCUITO_CODIGO,CODIGO_ESCUDERIA ,Q6_Cant_Paradas_XCirc_Xanio_XEscuderia,Anio)
(select CI.CIRCUITO_CODIGO,E.CODIGO_ESCUDERIA,COUNT(PB.CODIGO_PARADA_BOX) AS "Cantidad",
YEAR(CR.CARRERA_FECHA) as "ANIO"
from COSMICOS.PARADA_BOX PB
JOIN COSMICOS.AUTO_POR_CARRERA AC ON AC.CODIGO_AUTO_POR_CARRERA =  PB.CODIGO_AUTO_POR_CARRERA
JOIN COSMICOS.AUTO A ON AC.CODIGO_AUTO = A.CODIGO_AUTO
JOIN COSMICOS.ESCUDERIA E ON A.CODIGO_ESCUDERIA = E.CODIGO_ESCUDERIA
JOIN COSMICOS.CARRERA CR ON AC.CODIGO_CARRERA = CR.CODIGO_CARRERA
JOIN COSMICOS.CIRCUITO CI ON CI.CIRCUITO_CODIGO = CR.CIRCUITO_CODIGO
group by CI.CIRCUITO_CODIGO,E.CODIGO_ESCUDERIA,YEAR(CR.CARRERA_FECHA))


--Q7
--Los 3 circuitos donde se consume mayor cantidad en tiempo de paradas en boxes. 


insert into COSMICOS.BI_HechosPrincipal (CIRCUITO_CODIGO,  Q7_Tiempo_XParada_XCircuito)
select  c.CIRCUITO_CODIGO, sum(p.PARADA_BOX_TIEMPO)
from cosmicos.PARADA_BOX p 
join  cosmicos.CARRERA c on c.CODIGO_CARRERA =p.CODIGO_CARRERA
group by c.CIRCUITO_CODIGO  
order by sum(p.PARADA_BOX_TIEMPO) desc




--Q8
--Los 3 circuitos más peligrosos del año, en función mayor cantidad de incidentes. 
---------------------------------------------------------------------------------------------------

DROP PROCEDURE insetar_en_hehos_top3_circuitos_peligrosos_por_anio 
go

create procedure insetar_en_hehos_top3_circuitos_peligrosos_por_anio 
as begin
	declare @anio int
	declare @contador int
	declare  top3_circuitos cursor for
	SELECT DISTINCT YEAR(CARRERA_FECHA) FROM [COSMICOS].CARRERA ORDER BY 1 DESC
	
	open top3_circuitos
	fetch next FROM top3_circuitos 
	into @anio

	while @@FETCH_STATUS = 0
	begin
		insert into [COSMICOS].[BI_HechosPrincipal] ([CIRCUITO_CODIGO], [CODIGO_SECTOR], Anio,Q8_Cant_Incidente_XCircuito_XAnio)
		select TOP 3  C.CIRCUITO_CODIGO, [SECTOR_TIPO], YEAR(CAR.CARRERA_FECHA),COUNT(CODIGO_INCIDENTE) 
		FROM [COSMICOS].[CIRCUITO] C 
		JOIN [COSMICOS].[SECTOR] S ON C.CIRCUITO_CODIGO = S.CIRCUITO_CODIGO
		JOIN [COSMICOS].[INCIDENTE] I ON S.CODIGO_SECTOR = I.CODIGO_SECTOR 
		JOIN [COSMICOS].[CARRERA] CAR ON CAR.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO WHERE C.CIRCUITO_CODIGO in(
		SELECT C2.CIRCUITO_CODIGO 
		FROM [COSMICOS].[CIRCUITO] C2
		JOIN  [COSMICOS].[CARRERA] CAR ON C2.CIRCUITO_CODIGO = CAR.CIRCUITO_CODIGO
		WHERE YEAR(CAR.CARRERA_FECHA) = @anio)
		GROUP BY C.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE,[SECTOR_TIPO], YEAR(CAR.CARRERA_FECHA)
		ORDER BY 3 DESC,4 DESC
	fetch next FROM top3_circuitos 
	into @anio
	end
	CLOSE top3_circuitos
DEALLOCATE  top3_circuitos
end
go

EXEC insetar_en_hehos_top3_circuitos_peligrosos_por_anio 
go

--Q9
--Promedio de incidentes que presenta cada escudería por año en los distintos tipo de sectores. 

insert into [COSMICOS].[BI_HechosPrincipal](
CODIGO_ESCUDERIA, CODIGO_SECTOR, Anio ,Q8_Cant_Incidente_XCircuito_XAnio)
SELECT E.CODIGO_ESCUDERIA, S.CODIGO_SECTOR, YEAR(CAR.CARRERA_FECHA) AÑO, count(I.CODIGO_INCIDENTE) 
FROM [COSMICOS].[ESCUDERIA] E																									
JOIN [COSMICOS].[AUTO] A ON E.CODIGO_ESCUDERIA = A.CODIGO_ESCUDERIA																 
JOIN [COSMICOS].[AUTO_POR_INCIDENTE] AI ON A.CODIGO_AUTO = AI.CODIGO_AUTO_POR_CARRERA
JOIN [COSMICOS].[INCIDENTE] I ON I.CODIGO_INCIDENTE = AI.CODIGO_INCIDENTE
JOIN [COSMICOS].[CARRERA] CAR ON I.CODIGO_CARRERA = CAR.CODIGO_CARRERA
JOIN [COSMICOS].[SECTOR] S ON I.CODIGO_SECTOR = S.CODIGO_SECTOR
GROUP BY E.CODIGO_ESCUDERIA, S.CODIGO_SECTOR, YEAR(CARRERA_FECHA)
order by 1, 2, 3 desc
GO

--CREACION DE VISTAS
--------------------------------------------------------------------------------------------------------------------------------

create view MejorTiempoVuelta_XEscuderia_XCircuito_Xanio as
select top 3  Q2_MejorTiempoVuelta_XEscuderia_XCircuito_Xanio as tiempo, Anio ,HP.CODIGO_AUTO, DA.CODIGO_PILOTO, DA.AUTO_NUMERO, DA.MOTOR_NRO_SERIE, DA.CAJA_NRO_SERIE, HP.CODIGO_ESCUDERIA, DE.ESCUDERIA_NOMBRE CIRCUITO_CODIGO 
from COSMICOS.BI_HechosPrincipal HP
join COSMICOS.BI_DIMENSION_AUTO DA on DA.CODIGO_AUTO = HP.CODIGO_AUTO
JOIN COSMICOS.BI_DIMENSION_ESCUDERIA DE ON DE.CODIGO_ESCUDERIA = HP.CODIGO_ESCUDERIA
where Q2_MejorTiempoVuelta_XEscuderia_XCircuito_Xanio is not null
order by Q2_MejorTiempoVuelta_XEscuderia_XCircuito_Xanio
GO

--Q3
--Los 3 de circuitos con mayor consumo de combustible promedio. 
CREATE VIEW COSMICOS.Circuitos_Mayor_Consumo AS
SELECT TOP 3 H.CIRCUITO_CODIGO, C.CIRCUITO_NOMBRE, Q3_Prom_Consumo_Combustible_XCircuito AS COMBUSTIBLE_PROMEDIO 
FROM COSMICOS.BI_HechosPrincipal H
JOIN COSMICOS.BI_DIMENSION_CIRCUITO C ON H.CIRCUITO_CODIGO = C.CIRCUITO_CODIGO
ORDER BY Q3_Prom_Consumo_Combustible_XCircuito
GO

--Q4
--Máxima velocidad alcanzada por cada auto en cada tipo de sector de cada circuito. 
CREATE VIEW MaxVelocidadAutoSectorCircuito as
select HP.id_auto,HP.CIRCUITO_CODIGO, DS.SECTOR_TIPO ,HP.Q4_Max_Velocidad_XAuto_XSector_XCircuito from Cosmicos.BI_HechosPrincipal HP
JOIN COSMICOS.BI_DIMENSION_SECTOR DS on DS.CODIGO_SECTOR = HP.CODIGO_SECTOR
GO


--Q5
--Tiempo promedio que tardó cada escudería en las paradas por cuatrimestre. 
CREATE VIEW TiempoPromioParadaCuatri as
		select Q5_Tiempo_Prom_XEscuderia_Xanio_XSector,Cuatrimestre,Anio from Cosmicos.BI_HechosPrincipal HP
		join COSMICOS.BI_DIMENSION_ESCUDERIA ES on ES.CODIGO_ESCUDERIA = HP.CODIGO_ESCUDERIA  
GO
  
--Q6
--Cantidad de paradas por circuito por escudería por año. 
CREATE VIEW COSMICOS.cantParadasCircEscAnio as
		select DE.ESCUDERIA_NOMBRE,DI.CIRCUITO_NOMBRE, HP.Q6_Cant_Paradas_XCirc_Xanio_XEscuderia from Cosmicos.BI_HechosPrincipal HP
		join COSMICOS.BI_DIMENSION_ESCUDERIA DE ON DE.CODIGO_ESCUDERIA = HP.CODIGO_ESCUDERIA 
		JOIN COSMICOS.BI_DIMENSION_CIRCUITO DI ON DI.CIRCUITO_CODIGO = HP.CIRCUITO_CODIGO
GO

--Q7
--Los 3 circuitos donde se consume mayor cantidad en tiempo de paradas en boxes. 


create view Tiempo_XParada_XCircuito as
select top 3 CIRCUITO_CODIGO,  Q7_Tiempo_XParada_XCircuito as tiempo_parada
from COSMICOS.BI_HechosPrincipal
where Q7_Tiempo_XParada_XCircuito is not null 
order by Q7_Tiempo_XParada_XCircuito desc
GO

--Q8
--Los 3 circuitos más peligrosos del año, en función mayor cantidad de incidentes. 

CREATE VIEW V_circuitos_mas_peligrosos_por_año(
CODIGO_CICUITO , NOMBRE_CIRCUITO , TIPO_DE_SECTOR , CANT_INCIDENTES, AÑO
)AS
SELECT H.CIRCUITO_CODIGO, CIRCUITO_NOMBRE, DESCRIPCION, [Q8_Cant_Incidente_XCircuito_XAnio], ANIO
FROM [COSMICOS].[BI_HechosPrincipal] H
JOIN [COSMICOS].[CIRCUITO] C ON C.CIRCUITO_CODIGO = H.CIRCUITO_CODIGO
JOIN [COSMICOS].[TIPO_SECTOR] T ON T.SECTOR_TIPO = H.CODIGO_SECTOR
where Q8_Cant_Incidente_XCircuito_XAnio IS NOT NULL AND H.CODIGO_ESCUDERIA IS NULL
GO

select * from V_circuitos_mas_peligrosos_por_año

--Q9
--Promedio de incidentes que presenta cada escudería por año en los distintos tipo de sectores. 

CREATE VIEW V_promedio_incidentes_escuderia_por_año_por_tipo_de_sector(   -- aca se va a joinear con el tipo de sector para poder promediar la suma de todos los inicidentes de un tipo de sector y luego dividirlo por los codigos_sector
CODIGO_ESCUDERIA, NOMBRE_ESCUDERIA, TIPO_SECTOR, AÑO, PROMEDIO_INCIDENTES)
AS
SELECT H.CODIGO_ESCUDERIA, E.ESCUDERIA_NOMBRE, DESCRIPCION , H.Anio, SUM(H.Q8_Cant_Incidente_XCircuito_XAnio)/COUNT(H.CODIGO_SECTOR)
FROM [COSMICOS].HechosPrincipal H 
JOIN [COSMICOS].ESCUDERIA E ON E.CODIGO_ESCUDERIA = H.CODIGO_ESCUDERIA
JOIN [COSMICOS].SECTOR S ON S.CODIGO_SECTOR = H.CODIGO_SECTOR
JOIN [COSMICOS].TIPO_SECTOR T ON T.SECTOR_TIPO = S.SECTOR_TIPO
WHERE Q8_Cant_Incidente_XCircuito_XAnio IS NOT NULL AND H.CIRCUITO_CODIGO IS NULL
GROUP BY  H.CODIGO_ESCUDERIA, E.ESCUDERIA_NOMBRE, DESCRIPCION, H.Anio
GO

