CREATE SCHEMA [COSMICOS]
GO


CREATE TABLE [COSMICOS].[CIRCUITO] (
  [CIRCUITO_CODIGO] int PRIMARY KEY, --importado de tabla maestra
  [CIRCUITO_NOMBRE] nvarchar(255),
)
GO

CREATE TABLE [COSMICOS].[CARRERA] (
  [CODIGO_CARRERA] int PRIMARY KEY, --importado de tabla maestra
  [CARRERA_FECHA] date,
  [CARRERA_CLIMA] nvarchar(100),
  [CARRERA_TOTAL_CARRERA] decimal(18,2),
  [CARRERA_CANT_VUELTAS] int,
  [CIRCUITO_CODIGO] int NOT NULL
)
GO

CREATE TABLE [COSMICOS].[TIPO_SECTOR] (
  [SECTOR_TIPO] int PRIMARY KEY IDENTITY(1,1), --agregado por nosotros
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[SECTOR] (
  [CODIGO_SECTOR] int PRIMARY KEY, --importado de tabla maestra
  [SECTRO_DISTANCIA] decimal(18,2),
  [SECTOR_TIPO] int,
  [CIRCUITO_CODIGO] int NOT NULL
)
GO

CREATE TABLE [COSMICOS].[PILOTO] (
  [CODIGO_PILOTO] int PRIMARY KEY IDENTITY(1,1), --agregado por nosotros
  [PILOTO_NOMBRE] varchar(50),
  [PILOTO_APELLIDO] varchar(50),
  [PILOTO_NACIONALIDAD] varchar(50),
  [PILOTO_FECHA_NACIMIENTO] datetime
)
GO

CREATE TABLE [COSMICOS].[ESCUDERIA] (
  [CODIGO_ESCUDERIA] int PRIMARY KEY IDENTITY(1,1), --agregado por nosotros
  [ESCUDERIA_NOMBRE] varchar(50),
  [ESCUDERIA_NACIONALIDAD] varchar(50)
)
GO

CREATE TABLE [COSMICOS].[MOTOR] (
  [MOTOR_NRO_SERIE] nvarchar(255) PRIMARY KEY, --importado de tabla maestra
  [MOTOR_MODELO] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[CAJA] (
  [CAJA_NRO_SERIE] nvarchar(255) PRIMARY KEY, --importado de tabla maestra
  [CAJA_MODELO] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[FRENO] (
  [FRENO_NRO_SERIE] nvarchar(255) PRIMARY KEY, --importado de tabla maestra
  [FRENO_POSICION] nvarchar(255),
  [FRENO_TAMANIO_DISCO] decimal(18, 2)
)
GO

CREATE TABLE [COSMICOS].[TIPO_NEUMATICO] (
  [NEUMATICO_TIPO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[NEUMATICO] (
  [NEUMATICO_NRO_SERIE] nvarchar(255) PRIMARY KEY, --importado de tabla maestra
  [NEUMATICO_POSICION] nvarchar(255),
  [NEUMATICO_TIPO] int
)
GO

CREATE TABLE [COSMICOS].[AUTO] (
  [CODIGO_AUTO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [AUTO_NUMERO] int NOT NULL,
  [AUTO_MODELO] nvarchar(255),
  [CODIGO_PILOTO] int NOT NULL,
  [CODIGO_ESCUDERIA] int NOT NULL,
)
GO

CREATE TABLE [COSMICOS].[AUTO_POR_CARRERA] (
  [CODIGO_AUTO_POR_CARRERA] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [CODIGO_AUTO] int,
  [CODIGO_CARRERA] int,
  [MOTOR_NRO_SERIE] nvarchar(255) NULL,
  [CAJA_NRO_SERIE] nvarchar(255) NULL
)

CREATE TABLE [COSMICOS].[NEUMATICO_POR_AUTO] (
  [CODIGO_NEUMATICO_POR_AUTO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [NEUMATICO_NRO_SERIE] nvarchar(255),
  [CODIGO_AUTO_POR_CARRERA] int,
  [ACTIVO] bit,
)
GO

CREATE TABLE [COSMICOS].[FRENO_POR_AUTO] (
  [CODIGO_FRENO_POR_AUTO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [FRENO_NRO_SERIE] nvarchar(255),
  [CODIGO_AUTO_POR_CARRERA] int NOT NULL,
  [ACTIVO] bit,
)
GO


CREATE TABLE [COSMICOS].[BANDERA] (
  [CODIGO_BANDERA] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [COMPORTAMIENTO] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[TIPO_INCIDENTE] (
  [INCIDENTE_TIPO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [DESCRIPCION] nvarchar(255)
)
GO

CREATE TABLE [COSMICOS].[INCIDENTE] (
  [CODIGO_INCIDENTE] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [CODIGO_CARRERA] int NOT NULL,
  [CODIGO_SECTOR] int NOT NULL,
  [CODIGO_BANDERA] int
)
GO

CREATE TABLE [COSMICOS].[AUTO_POR_INCIDENTE] (
  [CODIGO_AUTO_POR_INCIDENTE] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [CODIGO_INCIDENTE] int NOT NULL,
  [CODIGO_AUTO_POR_CARRERA] int NOT NULL,
  [TIPO_INCIDENTE] int NOT NULL,
  [NRO_VUELTA] decimal(18, 0) NOT NULL,
  [INCIDENTE_TIEMPO] decimal(18, 2)
)
GO

CREATE TABLE [COSMICOS].[PARADA_BOX] (
  [CODIGO_PARADA_BOX] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [CODIGO_CARRERA] int NOT NULL,
  [CODIGO_AUTO_POR_CARRERA] int NOT NULL,
  [PARADA_BOX_VUELTA] decimal(18, 0),
  [PARADA_BOX_TIEMPO] decimal(18, 2)
)
GO

CREATE TABLE [COSMICOS].[NEUMATICO_POR_PARADA] (
  [CODIGO_NEUMATICO_POR_PARADA] int IDENTITY(1, 1), --agregado por nosotros
  [CODIGO_NEUMATICO_POR_AUTO] int,
  [CODIGO_PARADA_BOX] int NOT NULL,
  [TIPO] nvarchar(255) NOT NULL CHECK ([TIPO] IN ('VIEJO', 'NUEVO')),
  PRIMARY KEY ([CODIGO_NEUMATICO_POR_PARADA], [CODIGO_NEUMATICO_POR_AUTO])
)
GO

CREATE TABLE [COSMICOS].[TELEMETRIA_MOTOR] (
  [CODIGO_TELE_MOTOR] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [TELE_MOTOR_NRO_SERIE] nvarchar(255) NOT NULL,
  [TELE_MOTOR_POTENCIA] decimal(18, 6),
  [TELE_MOTOR_TEMP_ACEITE] decimal(18, 6),
  [TELE_MOTOR_TEMP_AGUA] decimal(18, 6),
  [TELE_MOTOR_RPM] decimal(18, 6)
)
GO

CREATE TABLE [COSMICOS].[TELEMETRIA_CAJA] (
  [CODIGO_TELE_CAJA] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [TELE_CAJA_NRO_SERIE] nvarchar(255) NOT NULL,
  [TELE_CAJA_TEMP_ACEITE] decimal(18, 2),
  [TELE_CAJA_RPM] decimal(18, 2),
  [TELE_CAJA_DESGASTE] decimal(18, 2)
)
GO

CREATE TABLE [COSMICOS].[TELEMETRIA_NEUMATICO] (
  [CODIGO_TELE_NEUMATICO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [TELE_NEUMATICO_NRO_SERIE] nvarchar(255) NOT NULL,
  [CODIGO_TELE] int NOT NULL,
  [TELE_NEUMATICO_PRESION] decimal(18, 6),
  [TELE_NEUMATICO_PROFUNDIDAD] decimal(18, 6),
  [TELE_NEUMATICO_TEMPERATURA] decimal(18, 6)
)
GO

CREATE TABLE [COSMICOS].[TELEMETRIA_FRENO] (
  [CODIGO_TELE_FRENO] int PRIMARY KEY IDENTITY(1, 1), --agregado por nosotros
  [TELE_FRENO_NRO_SERIE] nvarchar(255) NOT NULL,
  [CODIGO_TELE] int NOT NULL,
  [TELE_FRENO_TEMPERATURA] decimal(18, 2),
  [TELE_FRENO_GROSOR_PASTILLA] decimal(18, 2)
)
GO

CREATE TABLE [COSMICOS].[TELEMETRIA] (
  [CODIGO_TELE] int PRIMARY KEY, --importado de tabla maestra
  [CODIGO_AUTO_POR_CARRERA] int NOT NULL,
  [CODIGO_CARRERA] int NOT NULL,
  [CODIGO_SECTOR] int NOT NULL,
  [TELE_AUTO_DISTANCIA_CARRERA] decimal(18, 6),
  [TELE_AUTO_DISTANCIA_VUELTA] decimal(18, 2),
  [TELE_AUTO_TIEMPO_VUELTA] decimal(18, 10),
  [TELE_AUTO_POSICION] decimal(18, 0),
  [TELE_AUTO_VELOCIDAD] decimal(18, 2),
  [TELE_AUTO_NUMERO_VUELTA] decimal(18, 0),
  [TELE_AUTO_COMBUSTIBLE] decimal(18, 2),
  [CODIGO_TELE_MOTOR] int NOT NULL,
  [CODIGO_TELE_CAJA] int NOT NULL
)
GO

ALTER TABLE [COSMICOS].[CARRERA] ADD FOREIGN KEY ([CIRCUITO_CODIGO]) REFERENCES [COSMICOS].[CIRCUITO] ([CIRCUITO_CODIGO])
GO

ALTER TABLE [COSMICOS].[SECTOR] ADD FOREIGN KEY ([CIRCUITO_CODIGO]) REFERENCES [COSMICOS].[CIRCUITO] ([CIRCUITO_CODIGO])
GO

ALTER TABLE [COSMICOS].[SECTOR] ADD FOREIGN KEY ([SECTOR_TIPO]) REFERENCES [COSMICOS].[TIPO_SECTOR] ([SECTOR_TIPO])
GO

ALTER TABLE [COSMICOS].[NEUMATICO] ADD FOREIGN KEY ([NEUMATICO_TIPO]) REFERENCES [COSMICOS].[TIPO_NEUMATICO] ([NEUMATICO_TIPO])
GO

ALTER TABLE [COSMICOS].[AUTO] ADD FOREIGN KEY ([CODIGO_PILOTO]) REFERENCES [COSMICOS].[PILOTO] ([CODIGO_PILOTO])
GO

ALTER TABLE [COSMICOS].[AUTO] ADD FOREIGN KEY ([CODIGO_ESCUDERIA]) REFERENCES [COSMICOS].[ESCUDERIA] ([CODIGO_ESCUDERIA])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_CARRERA] ADD FOREIGN KEY ([CODIGO_AUTO]) REFERENCES [COSMICOS].[AUTO] ([CODIGO_AUTO])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_CARRERA] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [COSMICOS].[CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_CARRERA] ADD FOREIGN KEY ([MOTOR_NRO_SERIE]) REFERENCES [COSMICOS].[MOTOR] ([MOTOR_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_CARRERA] ADD FOREIGN KEY ([CAJA_NRO_SERIE]) REFERENCES [COSMICOS].[CAJA] ([CAJA_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[NEUMATICO_POR_AUTO] ADD FOREIGN KEY ([NEUMATICO_NRO_SERIE]) REFERENCES [COSMICOS].[NEUMATICO] ([NEUMATICO_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[NEUMATICO_POR_AUTO] ADD FOREIGN KEY ([CODIGO_AUTO_POR_CARRERA]) REFERENCES [COSMICOS].[AUTO_POR_CARRERA] ([CODIGO_AUTO_POR_CARRERA])
GO

ALTER TABLE [COSMICOS].[FRENO_POR_AUTO] ADD FOREIGN KEY ([FRENO_NRO_SERIE]) REFERENCES [COSMICOS].[FRENO] ([FRENO_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[FRENO_POR_AUTO] ADD FOREIGN KEY ([CODIGO_AUTO_POR_CARRERA]) REFERENCES [COSMICOS].[AUTO_POR_CARRERA] ([CODIGO_AUTO_POR_CARRERA])
GO

ALTER TABLE [COSMICOS].[INCIDENTE] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [COSMICOS].[CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [COSMICOS].[INCIDENTE] ADD FOREIGN KEY ([CODIGO_SECTOR]) REFERENCES [COSMICOS].[SECTOR] ([CODIGO_SECTOR])
GO

ALTER TABLE [COSMICOS].[INCIDENTE] ADD FOREIGN KEY ([CODIGO_BANDERA]) REFERENCES [COSMICOS].[BANDERA] ([CODIGO_BANDERA])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([CODIGO_INCIDENTE]) REFERENCES [COSMICOS].[INCIDENTE] ([CODIGO_INCIDENTE])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([CODIGO_AUTO_POR_CARRERA]) REFERENCES [COSMICOS].[AUTO_POR_CARRERA] ([CODIGO_AUTO_POR_CARRERA])
GO

ALTER TABLE [COSMICOS].[AUTO_POR_INCIDENTE] ADD FOREIGN KEY ([TIPO_INCIDENTE]) REFERENCES [COSMICOS].[TIPO_INCIDENTE] ([INCIDENTE_TIPO])
GO

ALTER TABLE [COSMICOS].[PARADA_BOX] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [COSMICOS].[CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [COSMICOS].[PARADA_BOX] ADD FOREIGN KEY ([CODIGO_AUTO_POR_CARRERA]) REFERENCES [COSMICOS].[AUTO_POR_CARRERA] ([CODIGO_AUTO_POR_CARRERA])
GO

ALTER TABLE [COSMICOS].[NEUMATICO_POR_PARADA] ADD FOREIGN KEY ([CODIGO_NEUMATICO_POR_AUTO]) REFERENCES [COSMICOS].[NEUMATICO_POR_AUTO] ([CODIGO_NEUMATICO_POR_AUTO])
GO

ALTER TABLE [COSMICOS].[NEUMATICO_POR_PARADA] ADD FOREIGN KEY ([CODIGO_PARADA_BOX]) REFERENCES [COSMICOS].[PARADA_BOX] ([CODIGO_PARADA_BOX])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_MOTOR] ADD FOREIGN KEY ([TELE_MOTOR_NRO_SERIE]) REFERENCES [COSMICOS].[MOTOR] ([MOTOR_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_CAJA] ADD FOREIGN KEY ([TELE_CAJA_NRO_SERIE]) REFERENCES [COSMICOS].[CAJA] ([CAJA_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_NEUMATICO] ADD FOREIGN KEY ([TELE_NEUMATICO_NRO_SERIE]) REFERENCES [COSMICOS].[NEUMATICO] ([NEUMATICO_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_NEUMATICO] ADD FOREIGN KEY ([CODIGO_TELE]) REFERENCES [COSMICOS].[TELEMETRIA] ([CODIGO_TELE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_FRENO] ADD FOREIGN KEY ([TELE_FRENO_NRO_SERIE]) REFERENCES [COSMICOS].[FRENO] ([FRENO_NRO_SERIE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA_FRENO] ADD FOREIGN KEY ([CODIGO_TELE]) REFERENCES [COSMICOS].[TELEMETRIA] ([CODIGO_TELE])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA] ADD FOREIGN KEY ([CODIGO_AUTO_POR_CARRERA]) REFERENCES [COSMICOS].[AUTO_POR_CARRERA] ([CODIGO_AUTO_POR_CARRERA])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA] ADD FOREIGN KEY ([CODIGO_CARRERA]) REFERENCES [COSMICOS].[CARRERA] ([CODIGO_CARRERA])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA] ADD FOREIGN KEY ([CODIGO_SECTOR]) REFERENCES [COSMICOS].[SECTOR] ([CODIGO_SECTOR])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA] ADD FOREIGN KEY ([CODIGO_TELE_MOTOR]) REFERENCES [COSMICOS].[TELEMETRIA_MOTOR] ([CODIGO_TELE_MOTOR])
GO

ALTER TABLE [COSMICOS].[TELEMETRIA] ADD FOREIGN KEY ([CODIGO_TELE_CAJA]) REFERENCES [COSMICOS].[TELEMETRIA_CAJA] ([CODIGO_TELE_CAJA])
GO
